// <auto-generated>
/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net;
using System.IO;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using GatewayApiSdk.Client;
using GatewayApiSdk.Logging;
using GatewayApiSdk.Model;
using System.Diagnostics.CodeAnalysis;

namespace GatewayApiSdk.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface ISearchDatasetsApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        SearchDatasetsApiEvents Events { get; }

        /// <summary>
        /// Search@datasets
        /// </summary>
        /// <remarks>
        /// Returns gateway datasets related to the provided query term(s)
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="searchDatasetsRequest">Submit search query</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ISearchDatasetsApiResponse"/>&gt;</returns>
        Task<ISearchDatasetsApiResponse> SearchDatasetsAsync(SearchDatasetsRequest searchDatasetsRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Search@datasets
        /// </summary>
        /// <remarks>
        /// Returns gateway datasets related to the provided query term(s)
        /// </remarks>
        /// <param name="searchDatasetsRequest">Submit search query</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ISearchDatasetsApiResponse"/>?&gt;</returns>
        Task<ISearchDatasetsApiResponse?> SearchDatasetsOrDefaultAsync(SearchDatasetsRequest searchDatasetsRequest, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="ISearchDatasetsApiResponse"/>
    /// </summary>
    public interface ISearchDatasetsApiResponse : GatewayApiSdk.Client.IApiResponse, IOk<GatewayApiSdk.Model.SearchDatasets200Response?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class SearchDatasetsApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnSearchDatasets;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorSearchDatasets;

        internal void ExecuteOnSearchDatasets(SearchDatasetsApi.SearchDatasetsApiResponse apiResponse)
        {
            OnSearchDatasets?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorSearchDatasets(Exception exception)
        {
            OnErrorSearchDatasets?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class SearchDatasetsApi : ISearchDatasetsApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<SearchDatasetsApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public SearchDatasetsApiEvents Events { get; }

        /// <summary>
        /// A token provider of type <see cref="BearerToken"/>
        /// </summary>
        public TokenProvider<BearerToken> BearerTokenProvider { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="SearchDatasetsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SearchDatasetsApi(ILogger<SearchDatasetsApi> logger, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, SearchDatasetsApiEvents searchDatasetsApiEvents,
            TokenProvider<BearerToken> bearerTokenProvider)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            Logger = logger;
            HttpClient = httpClient;
            Events = searchDatasetsApiEvents;
            BearerTokenProvider = bearerTokenProvider;
        }

        partial void FormatSearchDatasets(SearchDatasetsRequest searchDatasetsRequest);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="searchDatasetsRequest"></param>
        /// <returns></returns>
        private void ValidateSearchDatasets(SearchDatasetsRequest searchDatasetsRequest)
        {
            if (searchDatasetsRequest == null)
                throw new ArgumentNullException(nameof(searchDatasetsRequest));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="searchDatasetsRequest"></param>
        private void AfterSearchDatasetsDefaultImplementation(ISearchDatasetsApiResponse apiResponseLocalVar, SearchDatasetsRequest searchDatasetsRequest)
        {
            bool suppressDefaultLog = false;
            AfterSearchDatasets(ref suppressDefaultLog, apiResponseLocalVar, searchDatasetsRequest);
            if (!suppressDefaultLog)
                Logger.LogInformation(RestLogEvents.ApiRequestCompleted, "{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="searchDatasetsRequest"></param>
        partial void AfterSearchDatasets(ref bool suppressDefaultLog, ISearchDatasetsApiResponse apiResponseLocalVar, SearchDatasetsRequest searchDatasetsRequest);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="searchDatasetsRequest"></param>
        private void OnErrorSearchDatasetsDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, SearchDatasetsRequest searchDatasetsRequest)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorSearchDatasets(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, searchDatasetsRequest);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(RestLogEvents.ApiRequestFailed, exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="searchDatasetsRequest"></param>
        partial void OnErrorSearchDatasets(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, SearchDatasetsRequest searchDatasetsRequest);

        /// <summary>
        /// Search@datasets Returns gateway datasets related to the provided query term(s)
        /// </summary>
        /// <param name="searchDatasetsRequest">Submit search query</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ISearchDatasetsApiResponse"/>&gt;</returns>
        public async Task<ISearchDatasetsApiResponse?> SearchDatasetsOrDefaultAsync(SearchDatasetsRequest searchDatasetsRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await SearchDatasetsAsync(searchDatasetsRequest, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Search@datasets Returns gateway datasets related to the provided query term(s)
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="searchDatasetsRequest">Submit search query</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ISearchDatasetsApiResponse"/>&gt;</returns>
        public async Task<ISearchDatasetsApiResponse> SearchDatasetsAsync(SearchDatasetsRequest searchDatasetsRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateSearchDatasets(searchDatasetsRequest);

                FormatSearchDatasets(searchDatasetsRequest);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/api/v1/search/datasets"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/api/v1/search/datasets");

                    httpRequestMessageLocalVar.Content = (searchDatasetsRequest as object) is GatewayApiSdk.Client.FileParameter fileParameterLocalVar
                        ? httpRequestMessageLocalVar.Content = new StreamContent(fileParameterLocalVar.Content)
                        : httpRequestMessageLocalVar.Content = new StringContent(JsonSerializer.Serialize(searchDatasetsRequest, _jsonSerializerOptions));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    BearerToken bearerTokenLocalVar1 = (BearerToken) await BearerTokenProvider.GetAsync(cancellation: cancellationToken).ConfigureAwait(false);

                    tokenBaseLocalVars.Add(bearerTokenLocalVar1);

                    bearerTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar, "");

                    string[] contentTypes = new string[] {
                        "application/json"
                    };

                    string? contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Post;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        SearchDatasetsApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(Logger, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/api/v1/search/datasets", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterSearchDatasetsDefaultImplementation(apiResponseLocalVar, searchDatasetsRequest);

                        Events.ExecuteOnSearchDatasets(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorSearchDatasetsDefaultImplementation(e, "/api/v1/search/datasets", uriBuilderLocalVar.Path, searchDatasetsRequest);
                Events.ExecuteOnErrorSearchDatasets(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="SearchDatasetsApiResponse"/>
        /// </summary>
        public partial class SearchDatasetsApiResponse : GatewayApiSdk.Client.ApiResponse, ISearchDatasetsApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<SearchDatasetsApi> Logger { get; }

            /// <summary>
            /// The <see cref="SearchDatasetsApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public SearchDatasetsApiResponse(ILogger<SearchDatasetsApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="SearchDatasetsApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public SearchDatasetsApiResponse(ILogger<SearchDatasetsApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public GatewayApiSdk.Model.SearchDatasets200Response? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<GatewayApiSdk.Model.SearchDatasets200Response>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out GatewayApiSdk.Model.SearchDatasets200Response? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(RestLogEvents.ApiDeserializationFailed, exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
