// <auto-generated>
/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net;
using System.IO;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using GatewayApiSdk.Client;
using GatewayApiSdk.Logging;
using GatewayApiSdk.Model;
using System.Diagnostics.CodeAnalysis;

namespace GatewayApiSdk.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface ITeamDataAccessTemplateApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        TeamDataAccessTemplateApiEvents Events { get; }

        /// <summary>
        /// TeamDataAccessTemplateController@destroyFile
        /// </summary>
        /// <remarks>
        /// Delete a file associated with a DAR template
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="teamId">Team id</param>
        /// <param name="id">DAR template id</param>
        /// <param name="fileId">File id</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IDeleteTeamDarTemplateFileApiResponse"/>&gt;</returns>
        Task<IDeleteTeamDarTemplateFileApiResponse> DeleteTeamDarTemplateFileAsync(int teamId, int id, string fileId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// TeamDataAccessTemplateController@destroyFile
        /// </summary>
        /// <remarks>
        /// Delete a file associated with a DAR template
        /// </remarks>
        /// <param name="teamId">Team id</param>
        /// <param name="id">DAR template id</param>
        /// <param name="fileId">File id</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IDeleteTeamDarTemplateFileApiResponse"/>?&gt;</returns>
        Task<IDeleteTeamDarTemplateFileApiResponse?> DeleteTeamDarTemplateFileOrDefaultAsync(int teamId, int id, string fileId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// TeamDataAccessTemplateController@index
        /// </summary>
        /// <remarks>
        /// List of dar templates belonging to a team
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="teamId">Team id</param>
        /// <param name="published">Template publication status to filter by (true, false) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IFetchTeamDarTemplatesApiResponse"/>&gt;</returns>
        Task<IFetchTeamDarTemplatesApiResponse> FetchTeamDarTemplatesAsync(int teamId, Option<string> published = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// TeamDataAccessTemplateController@index
        /// </summary>
        /// <remarks>
        /// List of dar templates belonging to a team
        /// </remarks>
        /// <param name="teamId">Team id</param>
        /// <param name="published">Template publication status to filter by (true, false) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IFetchTeamDarTemplatesApiResponse"/>?&gt;</returns>
        Task<IFetchTeamDarTemplatesApiResponse?> FetchTeamDarTemplatesOrDefaultAsync(int teamId, Option<string> published = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// TeamDataAccessTemplateController@count
        /// </summary>
        /// <remarks>
        /// Get Counts for distinct entries of a field in the model
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="teamId">Team id</param>
        /// <param name="field">name of the field to perform a count on</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ITeamDarTemplateCountUniqueFieldsApiResponse"/>&gt;</returns>
        Task<ITeamDarTemplateCountUniqueFieldsApiResponse> TeamDarTemplateCountUniqueFieldsAsync(int teamId, string field, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// TeamDataAccessTemplateController@count
        /// </summary>
        /// <remarks>
        /// Get Counts for distinct entries of a field in the model
        /// </remarks>
        /// <param name="teamId">Team id</param>
        /// <param name="field">name of the field to perform a count on</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ITeamDarTemplateCountUniqueFieldsApiResponse"/>?&gt;</returns>
        Task<ITeamDarTemplateCountUniqueFieldsApiResponse?> TeamDarTemplateCountUniqueFieldsOrDefaultAsync(int teamId, string field, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="IDeleteTeamDarTemplateFileApiResponse"/>
    /// </summary>
    public interface IDeleteTeamDarTemplateFileApiResponse : GatewayApiSdk.Client.IApiResponse, IUnauthorized<GatewayApiSdk.Model.CreateTeamCollections401Response?>, IOk<GatewayApiSdk.Model.DeleteAliases200Response?>, IInternalServerError<GatewayApiSdk.Model.CreateAliases500Response?>
    {
        /// <summary>
        /// Returns true if the response is 401 Unauthorized
        /// </summary>
        /// <returns></returns>
        bool IsUnauthorized { get; }

        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 500 InternalServerError
        /// </summary>
        /// <returns></returns>
        bool IsInternalServerError { get; }
    }

    /// <summary>
    /// The <see cref="IFetchTeamDarTemplatesApiResponse"/>
    /// </summary>
    public interface IFetchTeamDarTemplatesApiResponse : GatewayApiSdk.Client.IApiResponse, IOk<GatewayApiSdk.Model.FetchDarTemplates200Response?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }
    }

    /// <summary>
    /// The <see cref="ITeamDarTemplateCountUniqueFieldsApiResponse"/>
    /// </summary>
    public interface ITeamDarTemplateCountUniqueFieldsApiResponse : GatewayApiSdk.Client.IApiResponse, IOk<GatewayApiSdk.Model.CountUniqueFieldsCollections200Response?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class TeamDataAccessTemplateApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnDeleteTeamDarTemplateFile;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorDeleteTeamDarTemplateFile;

        internal void ExecuteOnDeleteTeamDarTemplateFile(TeamDataAccessTemplateApi.DeleteTeamDarTemplateFileApiResponse apiResponse)
        {
            OnDeleteTeamDarTemplateFile?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorDeleteTeamDarTemplateFile(Exception exception)
        {
            OnErrorDeleteTeamDarTemplateFile?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnFetchTeamDarTemplates;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorFetchTeamDarTemplates;

        internal void ExecuteOnFetchTeamDarTemplates(TeamDataAccessTemplateApi.FetchTeamDarTemplatesApiResponse apiResponse)
        {
            OnFetchTeamDarTemplates?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorFetchTeamDarTemplates(Exception exception)
        {
            OnErrorFetchTeamDarTemplates?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnTeamDarTemplateCountUniqueFields;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorTeamDarTemplateCountUniqueFields;

        internal void ExecuteOnTeamDarTemplateCountUniqueFields(TeamDataAccessTemplateApi.TeamDarTemplateCountUniqueFieldsApiResponse apiResponse)
        {
            OnTeamDarTemplateCountUniqueFields?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorTeamDarTemplateCountUniqueFields(Exception exception)
        {
            OnErrorTeamDarTemplateCountUniqueFields?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class TeamDataAccessTemplateApi : ITeamDataAccessTemplateApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<TeamDataAccessTemplateApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public TeamDataAccessTemplateApiEvents Events { get; }

        /// <summary>
        /// A token provider of type <see cref="BearerToken"/>
        /// </summary>
        public TokenProvider<BearerToken> BearerTokenProvider { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="TeamDataAccessTemplateApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TeamDataAccessTemplateApi(ILogger<TeamDataAccessTemplateApi> logger, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, TeamDataAccessTemplateApiEvents teamDataAccessTemplateApiEvents,
            TokenProvider<BearerToken> bearerTokenProvider)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            Logger = logger;
            HttpClient = httpClient;
            Events = teamDataAccessTemplateApiEvents;
            BearerTokenProvider = bearerTokenProvider;
        }

        partial void FormatDeleteTeamDarTemplateFile(ref int teamId, ref int id, ref string fileId);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="fileId"></param>
        /// <returns></returns>
        private void ValidateDeleteTeamDarTemplateFile(string fileId)
        {
            if (fileId == null)
                throw new ArgumentNullException(nameof(fileId));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="teamId"></param>
        /// <param name="id"></param>
        /// <param name="fileId"></param>
        private void AfterDeleteTeamDarTemplateFileDefaultImplementation(IDeleteTeamDarTemplateFileApiResponse apiResponseLocalVar, int teamId, int id, string fileId)
        {
            bool suppressDefaultLog = false;
            AfterDeleteTeamDarTemplateFile(ref suppressDefaultLog, apiResponseLocalVar, teamId, id, fileId);
            if (!suppressDefaultLog)
                Logger.LogInformation(RestLogEvents.ApiRequestCompleted, "{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="teamId"></param>
        /// <param name="id"></param>
        /// <param name="fileId"></param>
        partial void AfterDeleteTeamDarTemplateFile(ref bool suppressDefaultLog, IDeleteTeamDarTemplateFileApiResponse apiResponseLocalVar, int teamId, int id, string fileId);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="teamId"></param>
        /// <param name="id"></param>
        /// <param name="fileId"></param>
        private void OnErrorDeleteTeamDarTemplateFileDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, int teamId, int id, string fileId)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorDeleteTeamDarTemplateFile(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, teamId, id, fileId);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(RestLogEvents.ApiRequestFailed, exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="teamId"></param>
        /// <param name="id"></param>
        /// <param name="fileId"></param>
        partial void OnErrorDeleteTeamDarTemplateFile(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, int teamId, int id, string fileId);

        /// <summary>
        /// TeamDataAccessTemplateController@destroyFile Delete a file associated with a DAR template
        /// </summary>
        /// <param name="teamId">Team id</param>
        /// <param name="id">DAR template id</param>
        /// <param name="fileId">File id</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IDeleteTeamDarTemplateFileApiResponse"/>&gt;</returns>
        public async Task<IDeleteTeamDarTemplateFileApiResponse?> DeleteTeamDarTemplateFileOrDefaultAsync(int teamId, int id, string fileId, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await DeleteTeamDarTemplateFileAsync(teamId, id, fileId, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// TeamDataAccessTemplateController@destroyFile Delete a file associated with a DAR template
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="teamId">Team id</param>
        /// <param name="id">DAR template id</param>
        /// <param name="fileId">File id</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IDeleteTeamDarTemplateFileApiResponse"/>&gt;</returns>
        public async Task<IDeleteTeamDarTemplateFileApiResponse> DeleteTeamDarTemplateFileAsync(int teamId, int id, string fileId, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateDeleteTeamDarTemplateFile(fileId);

                FormatDeleteTeamDarTemplateFile(ref teamId, ref id, ref fileId);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/api/v1/teams/{teamId}/dar/templates/{id}/files/{fileId}"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/api/v1/teams/{teamId}/dar/templates/{id}/files/{fileId}");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BteamId%7D", Uri.EscapeDataString(teamId.ToString()));
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7Bid%7D", Uri.EscapeDataString(id.ToString()));
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BfileId%7D", Uri.EscapeDataString(fileId.ToString()));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    BearerToken bearerTokenLocalVar1 = (BearerToken) await BearerTokenProvider.GetAsync(cancellation: cancellationToken).ConfigureAwait(false);

                    tokenBaseLocalVars.Add(bearerTokenLocalVar1);

                    bearerTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar, "");

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Delete;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        DeleteTeamDarTemplateFileApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(Logger, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/api/v1/teams/{teamId}/dar/templates/{id}/files/{fileId}", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterDeleteTeamDarTemplateFileDefaultImplementation(apiResponseLocalVar, teamId, id, fileId);

                        Events.ExecuteOnDeleteTeamDarTemplateFile(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorDeleteTeamDarTemplateFileDefaultImplementation(e, "/api/v1/teams/{teamId}/dar/templates/{id}/files/{fileId}", uriBuilderLocalVar.Path, teamId, id, fileId);
                Events.ExecuteOnErrorDeleteTeamDarTemplateFile(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="DeleteTeamDarTemplateFileApiResponse"/>
        /// </summary>
        public partial class DeleteTeamDarTemplateFileApiResponse : GatewayApiSdk.Client.ApiResponse, IDeleteTeamDarTemplateFileApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<TeamDataAccessTemplateApi> Logger { get; }

            /// <summary>
            /// The <see cref="DeleteTeamDarTemplateFileApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public DeleteTeamDarTemplateFileApiResponse(ILogger<TeamDataAccessTemplateApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="DeleteTeamDarTemplateFileApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public DeleteTeamDarTemplateFileApiResponse(ILogger<TeamDataAccessTemplateApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 401 Unauthorized
            /// </summary>
            /// <returns></returns>
            public bool IsUnauthorized => 401 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 401 Unauthorized
            /// </summary>
            /// <returns></returns>
            public GatewayApiSdk.Model.CreateTeamCollections401Response? Unauthorized()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsUnauthorized
                    ? System.Text.Json.JsonSerializer.Deserialize<GatewayApiSdk.Model.CreateTeamCollections401Response>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 401 Unauthorized and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnauthorized([NotNullWhen(true)]out GatewayApiSdk.Model.CreateTeamCollections401Response? result)
            {
                result = null;

                try
                {
                    result = Unauthorized();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)401);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public GatewayApiSdk.Model.DeleteAliases200Response? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<GatewayApiSdk.Model.DeleteAliases200Response>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out GatewayApiSdk.Model.DeleteAliases200Response? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public bool IsInternalServerError => 500 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public GatewayApiSdk.Model.CreateAliases500Response? InternalServerError()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsInternalServerError
                    ? System.Text.Json.JsonSerializer.Deserialize<GatewayApiSdk.Model.CreateAliases500Response>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryInternalServerError([NotNullWhen(true)]out GatewayApiSdk.Model.CreateAliases500Response? result)
            {
                result = null;

                try
                {
                    result = InternalServerError();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)500);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(RestLogEvents.ApiDeserializationFailed, exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatFetchTeamDarTemplates(ref int teamId, ref Option<string> published);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="published"></param>
        /// <returns></returns>
        private void ValidateFetchTeamDarTemplates(Option<string> published)
        {
            if (published.IsSet && published.Value == null)
                throw new ArgumentNullException(nameof(published));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="teamId"></param>
        /// <param name="published"></param>
        private void AfterFetchTeamDarTemplatesDefaultImplementation(IFetchTeamDarTemplatesApiResponse apiResponseLocalVar, int teamId, Option<string> published)
        {
            bool suppressDefaultLog = false;
            AfterFetchTeamDarTemplates(ref suppressDefaultLog, apiResponseLocalVar, teamId, published);
            if (!suppressDefaultLog)
                Logger.LogInformation(RestLogEvents.ApiRequestCompleted, "{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="teamId"></param>
        /// <param name="published"></param>
        partial void AfterFetchTeamDarTemplates(ref bool suppressDefaultLog, IFetchTeamDarTemplatesApiResponse apiResponseLocalVar, int teamId, Option<string> published);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="teamId"></param>
        /// <param name="published"></param>
        private void OnErrorFetchTeamDarTemplatesDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, int teamId, Option<string> published)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorFetchTeamDarTemplates(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, teamId, published);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(RestLogEvents.ApiRequestFailed, exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="teamId"></param>
        /// <param name="published"></param>
        partial void OnErrorFetchTeamDarTemplates(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, int teamId, Option<string> published);

        /// <summary>
        /// TeamDataAccessTemplateController@index List of dar templates belonging to a team
        /// </summary>
        /// <param name="teamId">Team id</param>
        /// <param name="published">Template publication status to filter by (true, false) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IFetchTeamDarTemplatesApiResponse"/>&gt;</returns>
        public async Task<IFetchTeamDarTemplatesApiResponse?> FetchTeamDarTemplatesOrDefaultAsync(int teamId, Option<string> published = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await FetchTeamDarTemplatesAsync(teamId, published, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// TeamDataAccessTemplateController@index List of dar templates belonging to a team
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="teamId">Team id</param>
        /// <param name="published">Template publication status to filter by (true, false) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IFetchTeamDarTemplatesApiResponse"/>&gt;</returns>
        public async Task<IFetchTeamDarTemplatesApiResponse> FetchTeamDarTemplatesAsync(int teamId, Option<string> published = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateFetchTeamDarTemplates(published);

                FormatFetchTeamDarTemplates(ref teamId, ref published);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/api/v1/teams/{teamId}/dar/templates"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/api/v1/teams/{teamId}/dar/templates");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BteamId%7D", Uri.EscapeDataString(teamId.ToString()));

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    if (published.IsSet)
                        parseQueryStringLocalVar["published"] = ClientUtils.ParameterToString(published.Value);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    BearerToken bearerTokenLocalVar1 = (BearerToken) await BearerTokenProvider.GetAsync(cancellation: cancellationToken).ConfigureAwait(false);

                    tokenBaseLocalVars.Add(bearerTokenLocalVar1);

                    bearerTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar, "");

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        FetchTeamDarTemplatesApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(Logger, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/api/v1/teams/{teamId}/dar/templates", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterFetchTeamDarTemplatesDefaultImplementation(apiResponseLocalVar, teamId, published);

                        Events.ExecuteOnFetchTeamDarTemplates(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorFetchTeamDarTemplatesDefaultImplementation(e, "/api/v1/teams/{teamId}/dar/templates", uriBuilderLocalVar.Path, teamId, published);
                Events.ExecuteOnErrorFetchTeamDarTemplates(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="FetchTeamDarTemplatesApiResponse"/>
        /// </summary>
        public partial class FetchTeamDarTemplatesApiResponse : GatewayApiSdk.Client.ApiResponse, IFetchTeamDarTemplatesApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<TeamDataAccessTemplateApi> Logger { get; }

            /// <summary>
            /// The <see cref="FetchTeamDarTemplatesApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public FetchTeamDarTemplatesApiResponse(ILogger<TeamDataAccessTemplateApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="FetchTeamDarTemplatesApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public FetchTeamDarTemplatesApiResponse(ILogger<TeamDataAccessTemplateApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public GatewayApiSdk.Model.FetchDarTemplates200Response? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<GatewayApiSdk.Model.FetchDarTemplates200Response>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out GatewayApiSdk.Model.FetchDarTemplates200Response? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(RestLogEvents.ApiDeserializationFailed, exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatTeamDarTemplateCountUniqueFields(ref int teamId, ref string field);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="field"></param>
        /// <returns></returns>
        private void ValidateTeamDarTemplateCountUniqueFields(string field)
        {
            if (field == null)
                throw new ArgumentNullException(nameof(field));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="teamId"></param>
        /// <param name="field"></param>
        private void AfterTeamDarTemplateCountUniqueFieldsDefaultImplementation(ITeamDarTemplateCountUniqueFieldsApiResponse apiResponseLocalVar, int teamId, string field)
        {
            bool suppressDefaultLog = false;
            AfterTeamDarTemplateCountUniqueFields(ref suppressDefaultLog, apiResponseLocalVar, teamId, field);
            if (!suppressDefaultLog)
                Logger.LogInformation(RestLogEvents.ApiRequestCompleted, "{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="teamId"></param>
        /// <param name="field"></param>
        partial void AfterTeamDarTemplateCountUniqueFields(ref bool suppressDefaultLog, ITeamDarTemplateCountUniqueFieldsApiResponse apiResponseLocalVar, int teamId, string field);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="teamId"></param>
        /// <param name="field"></param>
        private void OnErrorTeamDarTemplateCountUniqueFieldsDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, int teamId, string field)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorTeamDarTemplateCountUniqueFields(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, teamId, field);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(RestLogEvents.ApiRequestFailed, exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="teamId"></param>
        /// <param name="field"></param>
        partial void OnErrorTeamDarTemplateCountUniqueFields(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, int teamId, string field);

        /// <summary>
        /// TeamDataAccessTemplateController@count Get Counts for distinct entries of a field in the model
        /// </summary>
        /// <param name="teamId">Team id</param>
        /// <param name="field">name of the field to perform a count on</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ITeamDarTemplateCountUniqueFieldsApiResponse"/>&gt;</returns>
        public async Task<ITeamDarTemplateCountUniqueFieldsApiResponse?> TeamDarTemplateCountUniqueFieldsOrDefaultAsync(int teamId, string field, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await TeamDarTemplateCountUniqueFieldsAsync(teamId, field, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// TeamDataAccessTemplateController@count Get Counts for distinct entries of a field in the model
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="teamId">Team id</param>
        /// <param name="field">name of the field to perform a count on</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="ITeamDarTemplateCountUniqueFieldsApiResponse"/>&gt;</returns>
        public async Task<ITeamDarTemplateCountUniqueFieldsApiResponse> TeamDarTemplateCountUniqueFieldsAsync(int teamId, string field, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateTeamDarTemplateCountUniqueFields(field);

                FormatTeamDarTemplateCountUniqueFields(ref teamId, ref field);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/api/v1/teams/{teamId}/dar/templates/count/{field}"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/api/v1/teams/{teamId}/dar/templates/count/{field}");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BteamId%7D", Uri.EscapeDataString(teamId.ToString()));
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7Bfield%7D", Uri.EscapeDataString(field.ToString()));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    BearerToken bearerTokenLocalVar1 = (BearerToken) await BearerTokenProvider.GetAsync(cancellation: cancellationToken).ConfigureAwait(false);

                    tokenBaseLocalVars.Add(bearerTokenLocalVar1);

                    bearerTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar, "");

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        TeamDarTemplateCountUniqueFieldsApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(Logger, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/api/v1/teams/{teamId}/dar/templates/count/{field}", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterTeamDarTemplateCountUniqueFieldsDefaultImplementation(apiResponseLocalVar, teamId, field);

                        Events.ExecuteOnTeamDarTemplateCountUniqueFields(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorTeamDarTemplateCountUniqueFieldsDefaultImplementation(e, "/api/v1/teams/{teamId}/dar/templates/count/{field}", uriBuilderLocalVar.Path, teamId, field);
                Events.ExecuteOnErrorTeamDarTemplateCountUniqueFields(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="TeamDarTemplateCountUniqueFieldsApiResponse"/>
        /// </summary>
        public partial class TeamDarTemplateCountUniqueFieldsApiResponse : GatewayApiSdk.Client.ApiResponse, ITeamDarTemplateCountUniqueFieldsApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<TeamDataAccessTemplateApi> Logger { get; }

            /// <summary>
            /// The <see cref="TeamDarTemplateCountUniqueFieldsApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public TeamDarTemplateCountUniqueFieldsApiResponse(ILogger<TeamDataAccessTemplateApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="TeamDarTemplateCountUniqueFieldsApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public TeamDarTemplateCountUniqueFieldsApiResponse(ILogger<TeamDataAccessTemplateApi> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public GatewayApiSdk.Model.CountUniqueFieldsCollections200Response? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<GatewayApiSdk.Model.CountUniqueFieldsCollections200Response>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out GatewayApiSdk.Model.CountUniqueFieldsCollections200Response? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(RestLogEvents.ApiDeserializationFailed, exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
