// <auto-generated>
/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using GatewayApiSdk.Client;

namespace GatewayApiSdk.Model
{
    /// <summary>
    /// A5f6e0a9550d3c58c50dda55412cd051Request
    /// </summary>
    public partial class A5f6e0a9550d3c58c50dda55412cd051Request : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="A5f6e0a9550d3c58c50dda55412cd051Request" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="enabled">enabled</param>
        [JsonConstructor]
        public A5f6e0a9550d3c58c50dda55412cd051Request(Option<string?> name = default, Option<string?> enabled = default)
        {
            NameOption = name;
            EnabledOption = enabled;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        /* <example>Name</example> */
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Enabled
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EnabledOption { get; private set; }

        /// <summary>
        /// Gets or Sets Enabled
        /// </summary>
        /* <example>true</example> */
        [JsonPropertyName("enabled")]
        public string? Enabled { get { return this.EnabledOption.Value; } set { this.EnabledOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class A5f6e0a9550d3c58c50dda55412cd051Request {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="A5f6e0a9550d3c58c50dda55412cd051Request" />
    /// </summary>
    public partial class A5f6e0a9550d3c58c50dda55412cd051RequestJsonConverter : JsonConverter<A5f6e0a9550d3c58c50dda55412cd051Request>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="A5f6e0a9550d3c58c50dda55412cd051RequestJsonConverter" /> class.
        /// </summary>
        public A5f6e0a9550d3c58c50dda55412cd051RequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="A5f6e0a9550d3c58c50dda55412cd051Request" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override A5f6e0a9550d3c58c50dda55412cd051Request Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> enabled = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "enabled":
                            enabled = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class A5f6e0a9550d3c58c50dda55412cd051Request.");

            if (enabled.IsSet && enabled.Value == null)
                throw new ArgumentNullException(nameof(enabled), "Property is not nullable for class A5f6e0a9550d3c58c50dda55412cd051Request.");

            return new A5f6e0a9550d3c58c50dda55412cd051Request(name, enabled);
        }

        /// <summary>
        /// Serializes a <see cref="A5f6e0a9550d3c58c50dda55412cd051Request" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="a5f6e0a9550d3c58c50dda55412cd051Request"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, A5f6e0a9550d3c58c50dda55412cd051Request a5f6e0a9550d3c58c50dda55412cd051Request, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, a5f6e0a9550d3c58c50dda55412cd051Request, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="A5f6e0a9550d3c58c50dda55412cd051Request" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="a5f6e0a9550d3c58c50dda55412cd051Request"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, A5f6e0a9550d3c58c50dda55412cd051Request a5f6e0a9550d3c58c50dda55412cd051Request, JsonSerializerOptions jsonSerializerOptions)
        {
            if (a5f6e0a9550d3c58c50dda55412cd051Request.NameOption.IsSet && a5f6e0a9550d3c58c50dda55412cd051Request.Name == null)
                throw new ArgumentNullException(nameof(a5f6e0a9550d3c58c50dda55412cd051Request.Name), "Property is required for class A5f6e0a9550d3c58c50dda55412cd051Request.");

            if (a5f6e0a9550d3c58c50dda55412cd051Request.EnabledOption.IsSet && a5f6e0a9550d3c58c50dda55412cd051Request.Enabled == null)
                throw new ArgumentNullException(nameof(a5f6e0a9550d3c58c50dda55412cd051Request.Enabled), "Property is required for class A5f6e0a9550d3c58c50dda55412cd051Request.");

            if (a5f6e0a9550d3c58c50dda55412cd051Request.NameOption.IsSet)
                writer.WriteString("name", a5f6e0a9550d3c58c50dda55412cd051Request.Name);

            if (a5f6e0a9550d3c58c50dda55412cd051Request.EnabledOption.IsSet)
                writer.WriteString("enabled", a5f6e0a9550d3c58c50dda55412cd051Request.Enabled);
        }
    }
}
