// <auto-generated>
/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using GatewayApiSdk.Client;

namespace GatewayApiSdk.Model
{
    /// <summary>
    /// CreateCollectionsIntegrationsRequest
    /// </summary>
    public partial class CreateCollectionsIntegrationsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCollectionsIntegrationsRequest" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="description">description</param>
        /// <param name="imageLink">imageLink</param>
        /// <param name="enabled">enabled</param>
        /// <param name="keywords">keywords</param>
        /// <param name="datasets">datasets</param>
        /// <param name="dur">dur</param>
        /// <param name="publications">publications</param>
        /// <param name="public">public</param>
        [JsonConstructor]
        public CreateCollectionsIntegrationsRequest(Option<string?> name = default, Option<string?> description = default, Option<string?> imageLink = default, Option<bool?> enabled = default, Option<List<string>?> keywords = default, Option<List<CreateCollectionsIntegrationsRequestDatasetsInner>?> datasets = default, Option<List<CreateCollectionsIntegrationsRequestDatasetsInner>?> dur = default, Option<List<CreateCollectionsIntegrationsRequestDatasetsInner>?> publications = default, Option<bool?> @public = default)
        {
            NameOption = name;
            DescriptionOption = description;
            ImageLinkOption = imageLink;
            EnabledOption = enabled;
            KeywordsOption = keywords;
            DatasetsOption = datasets;
            DurOption = dur;
            PublicationsOption = publications;
            PublicOption = @public;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        /* <example>covid</example> */
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        /* <example>Dolorem voluptas consequatur nihil illum et sunt libero.</example> */
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption.Value; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of ImageLink
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ImageLinkOption { get; private set; }

        /// <summary>
        /// Gets or Sets ImageLink
        /// </summary>
        /* <example>https://via.placeholder.com/640x480.png/0022bb?text&#x3D;animals+cumque</example> */
        [JsonPropertyName("image_link")]
        public string? ImageLink { get { return this.ImageLinkOption.Value; } set { this.ImageLinkOption = new(value); } }

        /// <summary>
        /// Used to track the state of Enabled
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EnabledOption { get; private set; }

        /// <summary>
        /// Gets or Sets Enabled
        /// </summary>
        /* <example>true</example> */
        [JsonPropertyName("enabled")]
        public bool? Enabled { get { return this.EnabledOption.Value; } set { this.EnabledOption = new(value); } }

        /// <summary>
        /// Used to track the state of Keywords
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> KeywordsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Keywords
        /// </summary>
        /* <example>[]</example> */
        [JsonPropertyName("keywords")]
        public List<string>? Keywords { get { return this.KeywordsOption.Value; } set { this.KeywordsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Datasets
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<CreateCollectionsIntegrationsRequestDatasetsInner>?> DatasetsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Datasets
        /// </summary>
        /* <example>[]</example> */
        [JsonPropertyName("datasets")]
        public List<CreateCollectionsIntegrationsRequestDatasetsInner>? Datasets { get { return this.DatasetsOption.Value; } set { this.DatasetsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Dur
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<CreateCollectionsIntegrationsRequestDatasetsInner>?> DurOption { get; private set; }

        /// <summary>
        /// Gets or Sets Dur
        /// </summary>
        /* <example>[]</example> */
        [JsonPropertyName("dur")]
        public List<CreateCollectionsIntegrationsRequestDatasetsInner>? Dur { get { return this.DurOption.Value; } set { this.DurOption = new(value); } }

        /// <summary>
        /// Used to track the state of Publications
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<CreateCollectionsIntegrationsRequestDatasetsInner>?> PublicationsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Publications
        /// </summary>
        /* <example>[]</example> */
        [JsonPropertyName("publications")]
        public List<CreateCollectionsIntegrationsRequestDatasetsInner>? Publications { get { return this.PublicationsOption.Value; } set { this.PublicationsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Public
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> PublicOption { get; private set; }

        /// <summary>
        /// Gets or Sets Public
        /// </summary>
        /* <example>true</example> */
        [JsonPropertyName("public")]
        public bool? Public { get { return this.PublicOption.Value; } set { this.PublicOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateCollectionsIntegrationsRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  ImageLink: ").Append(ImageLink).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  Keywords: ").Append(Keywords).Append("\n");
            sb.Append("  Datasets: ").Append(Datasets).Append("\n");
            sb.Append("  Dur: ").Append(Dur).Append("\n");
            sb.Append("  Publications: ").Append(Publications).Append("\n");
            sb.Append("  Public: ").Append(Public).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateCollectionsIntegrationsRequest" />
    /// </summary>
    public partial class CreateCollectionsIntegrationsRequestJsonConverter : JsonConverter<CreateCollectionsIntegrationsRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCollectionsIntegrationsRequestJsonConverter" /> class.
        /// </summary>
        public CreateCollectionsIntegrationsRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="CreateCollectionsIntegrationsRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateCollectionsIntegrationsRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> description = default;
            Option<string?> imageLink = default;
            Option<bool?> enabled = default;
            Option<List<string>?> keywords = default;
            Option<List<CreateCollectionsIntegrationsRequestDatasetsInner>?> datasets = default;
            Option<List<CreateCollectionsIntegrationsRequestDatasetsInner>?> dur = default;
            Option<List<CreateCollectionsIntegrationsRequestDatasetsInner>?> publications = default;
            Option<bool?> varPublic = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "image_link":
                            imageLink = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "enabled":
                            enabled = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "keywords":
                            keywords = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "datasets":
                            datasets = new Option<List<CreateCollectionsIntegrationsRequestDatasetsInner>?>(JsonSerializer.Deserialize<List<CreateCollectionsIntegrationsRequestDatasetsInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "dur":
                            dur = new Option<List<CreateCollectionsIntegrationsRequestDatasetsInner>?>(JsonSerializer.Deserialize<List<CreateCollectionsIntegrationsRequestDatasetsInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "publications":
                            publications = new Option<List<CreateCollectionsIntegrationsRequestDatasetsInner>?>(JsonSerializer.Deserialize<List<CreateCollectionsIntegrationsRequestDatasetsInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "public":
                            varPublic = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class CreateCollectionsIntegrationsRequest.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class CreateCollectionsIntegrationsRequest.");

            if (imageLink.IsSet && imageLink.Value == null)
                throw new ArgumentNullException(nameof(imageLink), "Property is not nullable for class CreateCollectionsIntegrationsRequest.");

            if (enabled.IsSet && enabled.Value == null)
                throw new ArgumentNullException(nameof(enabled), "Property is not nullable for class CreateCollectionsIntegrationsRequest.");

            if (keywords.IsSet && keywords.Value == null)
                throw new ArgumentNullException(nameof(keywords), "Property is not nullable for class CreateCollectionsIntegrationsRequest.");

            if (datasets.IsSet && datasets.Value == null)
                throw new ArgumentNullException(nameof(datasets), "Property is not nullable for class CreateCollectionsIntegrationsRequest.");

            if (dur.IsSet && dur.Value == null)
                throw new ArgumentNullException(nameof(dur), "Property is not nullable for class CreateCollectionsIntegrationsRequest.");

            if (publications.IsSet && publications.Value == null)
                throw new ArgumentNullException(nameof(publications), "Property is not nullable for class CreateCollectionsIntegrationsRequest.");

            if (varPublic.IsSet && varPublic.Value == null)
                throw new ArgumentNullException(nameof(varPublic), "Property is not nullable for class CreateCollectionsIntegrationsRequest.");

            return new CreateCollectionsIntegrationsRequest(name, description, imageLink, enabled, keywords, datasets, dur, publications, varPublic);
        }

        /// <summary>
        /// Serializes a <see cref="CreateCollectionsIntegrationsRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createCollectionsIntegrationsRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateCollectionsIntegrationsRequest createCollectionsIntegrationsRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createCollectionsIntegrationsRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateCollectionsIntegrationsRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createCollectionsIntegrationsRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateCollectionsIntegrationsRequest createCollectionsIntegrationsRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createCollectionsIntegrationsRequest.NameOption.IsSet && createCollectionsIntegrationsRequest.Name == null)
                throw new ArgumentNullException(nameof(createCollectionsIntegrationsRequest.Name), "Property is required for class CreateCollectionsIntegrationsRequest.");

            if (createCollectionsIntegrationsRequest.DescriptionOption.IsSet && createCollectionsIntegrationsRequest.Description == null)
                throw new ArgumentNullException(nameof(createCollectionsIntegrationsRequest.Description), "Property is required for class CreateCollectionsIntegrationsRequest.");

            if (createCollectionsIntegrationsRequest.ImageLinkOption.IsSet && createCollectionsIntegrationsRequest.ImageLink == null)
                throw new ArgumentNullException(nameof(createCollectionsIntegrationsRequest.ImageLink), "Property is required for class CreateCollectionsIntegrationsRequest.");

            if (createCollectionsIntegrationsRequest.KeywordsOption.IsSet && createCollectionsIntegrationsRequest.Keywords == null)
                throw new ArgumentNullException(nameof(createCollectionsIntegrationsRequest.Keywords), "Property is required for class CreateCollectionsIntegrationsRequest.");

            if (createCollectionsIntegrationsRequest.DatasetsOption.IsSet && createCollectionsIntegrationsRequest.Datasets == null)
                throw new ArgumentNullException(nameof(createCollectionsIntegrationsRequest.Datasets), "Property is required for class CreateCollectionsIntegrationsRequest.");

            if (createCollectionsIntegrationsRequest.DurOption.IsSet && createCollectionsIntegrationsRequest.Dur == null)
                throw new ArgumentNullException(nameof(createCollectionsIntegrationsRequest.Dur), "Property is required for class CreateCollectionsIntegrationsRequest.");

            if (createCollectionsIntegrationsRequest.PublicationsOption.IsSet && createCollectionsIntegrationsRequest.Publications == null)
                throw new ArgumentNullException(nameof(createCollectionsIntegrationsRequest.Publications), "Property is required for class CreateCollectionsIntegrationsRequest.");

            if (createCollectionsIntegrationsRequest.NameOption.IsSet)
                writer.WriteString("name", createCollectionsIntegrationsRequest.Name);

            if (createCollectionsIntegrationsRequest.DescriptionOption.IsSet)
                writer.WriteString("description", createCollectionsIntegrationsRequest.Description);

            if (createCollectionsIntegrationsRequest.ImageLinkOption.IsSet)
                writer.WriteString("image_link", createCollectionsIntegrationsRequest.ImageLink);

            if (createCollectionsIntegrationsRequest.EnabledOption.IsSet)
                writer.WriteBoolean("enabled", createCollectionsIntegrationsRequest.EnabledOption.Value!.Value);

            if (createCollectionsIntegrationsRequest.KeywordsOption.IsSet)
            {
                writer.WritePropertyName("keywords");
                JsonSerializer.Serialize(writer, createCollectionsIntegrationsRequest.Keywords, jsonSerializerOptions);
            }
            if (createCollectionsIntegrationsRequest.DatasetsOption.IsSet)
            {
                writer.WritePropertyName("datasets");
                JsonSerializer.Serialize(writer, createCollectionsIntegrationsRequest.Datasets, jsonSerializerOptions);
            }
            if (createCollectionsIntegrationsRequest.DurOption.IsSet)
            {
                writer.WritePropertyName("dur");
                JsonSerializer.Serialize(writer, createCollectionsIntegrationsRequest.Dur, jsonSerializerOptions);
            }
            if (createCollectionsIntegrationsRequest.PublicationsOption.IsSet)
            {
                writer.WritePropertyName("publications");
                JsonSerializer.Serialize(writer, createCollectionsIntegrationsRequest.Publications, jsonSerializerOptions);
            }
            if (createCollectionsIntegrationsRequest.PublicOption.IsSet)
                writer.WriteBoolean("public", createCollectionsIntegrationsRequest.PublicOption.Value!.Value);
        }
    }
}
