// <auto-generated>
/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using GatewayApiSdk.Client;

namespace GatewayApiSdk.Model
{
    /// <summary>
    /// CreatePublicationsRequest
    /// </summary>
    public partial class CreatePublicationsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreatePublicationsRequest" /> class.
        /// </summary>
        /// <param name="paperTitle">paperTitle</param>
        /// <param name="authors">authors</param>
        /// <param name="yearOfPublication">yearOfPublication</param>
        /// <param name="paperDoi">paperDoi</param>
        /// <param name="publicationType">publicationType</param>
        /// <param name="journalName">journalName</param>
        /// <param name="abstract">abstract</param>
        /// <param name="url">url</param>
        /// <param name="mongoId">mongoId</param>
        /// <param name="datasets">datasets</param>
        /// <param name="tools">tools</param>
        [JsonConstructor]
        public CreatePublicationsRequest(Option<string?> paperTitle = default, Option<string?> authors = default, Option<string?> yearOfPublication = default, Option<string?> paperDoi = default, Option<string?> publicationType = default, Option<string?> journalName = default, Option<string?> @abstract = default, Option<string?> url = default, Option<string?> mongoId = default, Option<List<CreatePublicationsRequestDatasetsInner>?> datasets = default, Option<List<CreatePublicationsRequestToolsInner>?> tools = default)
        {
            PaperTitleOption = paperTitle;
            AuthorsOption = authors;
            YearOfPublicationOption = yearOfPublication;
            PaperDoiOption = paperDoi;
            PublicationTypeOption = publicationType;
            JournalNameOption = journalName;
            AbstractOption = @abstract;
            UrlOption = url;
            MongoIdOption = mongoId;
            DatasetsOption = datasets;
            ToolsOption = tools;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of PaperTitle
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PaperTitleOption { get; private set; }

        /// <summary>
        /// Gets or Sets PaperTitle
        /// </summary>
        /* <example>A title</example> */
        [JsonPropertyName("paper_title")]
        public string? PaperTitle { get { return this.PaperTitleOption.Value; } set { this.PaperTitleOption = new(value); } }

        /// <summary>
        /// Used to track the state of Authors
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AuthorsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Authors
        /// </summary>
        /* <example>Author A., Author B.</example> */
        [JsonPropertyName("authors")]
        public string? Authors { get { return this.AuthorsOption.Value; } set { this.AuthorsOption = new(value); } }

        /// <summary>
        /// Used to track the state of YearOfPublication
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> YearOfPublicationOption { get; private set; }

        /// <summary>
        /// Gets or Sets YearOfPublication
        /// </summary>
        /* <example>2024</example> */
        [JsonPropertyName("year_of_publication")]
        public string? YearOfPublication { get { return this.YearOfPublicationOption.Value; } set { this.YearOfPublicationOption = new(value); } }

        /// <summary>
        /// Used to track the state of PaperDoi
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PaperDoiOption { get; private set; }

        /// <summary>
        /// Gets or Sets PaperDoi
        /// </summary>
        /* <example>10.12345</example> */
        [JsonPropertyName("paper_doi")]
        public string? PaperDoi { get { return this.PaperDoiOption.Value; } set { this.PaperDoiOption = new(value); } }

        /// <summary>
        /// Used to track the state of PublicationType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PublicationTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets PublicationType
        /// </summary>
        /* <example>Journal article, Book</example> */
        [JsonPropertyName("publication_type")]
        public string? PublicationType { get { return this.PublicationTypeOption.Value; } set { this.PublicationTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of JournalName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> JournalNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets JournalName
        /// </summary>
        /* <example>A Journal</example> */
        [JsonPropertyName("journal_name")]
        public string? JournalName { get { return this.JournalNameOption.Value; } set { this.JournalNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Abstract
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AbstractOption { get; private set; }

        /// <summary>
        /// Gets or Sets Abstract
        /// </summary>
        /* <example>A long description of the paper</example> */
        [JsonPropertyName("abstract")]
        public string? Abstract { get { return this.AbstractOption.Value; } set { this.AbstractOption = new(value); } }

        /// <summary>
        /// Used to track the state of Url
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        /* <example>http://example</example> */
        [JsonPropertyName("url")]
        public string? Url { get { return this.UrlOption.Value; } set { this.UrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of MongoId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MongoIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets MongoId
        /// </summary>
        /* <example>38873389090594430</example> */
        [JsonPropertyName("mongo_id")]
        public string? MongoId { get { return this.MongoIdOption.Value; } set { this.MongoIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Datasets
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<CreatePublicationsRequestDatasetsInner>?> DatasetsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Datasets
        /// </summary>
        [JsonPropertyName("datasets")]
        public List<CreatePublicationsRequestDatasetsInner>? Datasets { get { return this.DatasetsOption.Value; } set { this.DatasetsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Tools
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<CreatePublicationsRequestToolsInner>?> ToolsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Tools
        /// </summary>
        [JsonPropertyName("tools")]
        public List<CreatePublicationsRequestToolsInner>? Tools { get { return this.ToolsOption.Value; } set { this.ToolsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreatePublicationsRequest {\n");
            sb.Append("  PaperTitle: ").Append(PaperTitle).Append("\n");
            sb.Append("  Authors: ").Append(Authors).Append("\n");
            sb.Append("  YearOfPublication: ").Append(YearOfPublication).Append("\n");
            sb.Append("  PaperDoi: ").Append(PaperDoi).Append("\n");
            sb.Append("  PublicationType: ").Append(PublicationType).Append("\n");
            sb.Append("  JournalName: ").Append(JournalName).Append("\n");
            sb.Append("  Abstract: ").Append(Abstract).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  MongoId: ").Append(MongoId).Append("\n");
            sb.Append("  Datasets: ").Append(Datasets).Append("\n");
            sb.Append("  Tools: ").Append(Tools).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreatePublicationsRequest" />
    /// </summary>
    public partial class CreatePublicationsRequestJsonConverter : JsonConverter<CreatePublicationsRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="CreatePublicationsRequestJsonConverter" /> class.
        /// </summary>
        public CreatePublicationsRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="CreatePublicationsRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreatePublicationsRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> paperTitle = default;
            Option<string?> authors = default;
            Option<string?> yearOfPublication = default;
            Option<string?> paperDoi = default;
            Option<string?> publicationType = default;
            Option<string?> journalName = default;
            Option<string?> varAbstract = default;
            Option<string?> url = default;
            Option<string?> mongoId = default;
            Option<List<CreatePublicationsRequestDatasetsInner>?> datasets = default;
            Option<List<CreatePublicationsRequestToolsInner>?> tools = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "paper_title":
                            paperTitle = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "authors":
                            authors = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "year_of_publication":
                            yearOfPublication = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "paper_doi":
                            paperDoi = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "publication_type":
                            publicationType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "journal_name":
                            journalName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "abstract":
                            varAbstract = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "url":
                            url = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "mongo_id":
                            mongoId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "datasets":
                            datasets = new Option<List<CreatePublicationsRequestDatasetsInner>?>(JsonSerializer.Deserialize<List<CreatePublicationsRequestDatasetsInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "tools":
                            tools = new Option<List<CreatePublicationsRequestToolsInner>?>(JsonSerializer.Deserialize<List<CreatePublicationsRequestToolsInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (paperTitle.IsSet && paperTitle.Value == null)
                throw new ArgumentNullException(nameof(paperTitle), "Property is not nullable for class CreatePublicationsRequest.");

            if (authors.IsSet && authors.Value == null)
                throw new ArgumentNullException(nameof(authors), "Property is not nullable for class CreatePublicationsRequest.");

            if (yearOfPublication.IsSet && yearOfPublication.Value == null)
                throw new ArgumentNullException(nameof(yearOfPublication), "Property is not nullable for class CreatePublicationsRequest.");

            if (paperDoi.IsSet && paperDoi.Value == null)
                throw new ArgumentNullException(nameof(paperDoi), "Property is not nullable for class CreatePublicationsRequest.");

            if (publicationType.IsSet && publicationType.Value == null)
                throw new ArgumentNullException(nameof(publicationType), "Property is not nullable for class CreatePublicationsRequest.");

            if (journalName.IsSet && journalName.Value == null)
                throw new ArgumentNullException(nameof(journalName), "Property is not nullable for class CreatePublicationsRequest.");

            if (varAbstract.IsSet && varAbstract.Value == null)
                throw new ArgumentNullException(nameof(varAbstract), "Property is not nullable for class CreatePublicationsRequest.");

            if (url.IsSet && url.Value == null)
                throw new ArgumentNullException(nameof(url), "Property is not nullable for class CreatePublicationsRequest.");

            if (mongoId.IsSet && mongoId.Value == null)
                throw new ArgumentNullException(nameof(mongoId), "Property is not nullable for class CreatePublicationsRequest.");

            if (datasets.IsSet && datasets.Value == null)
                throw new ArgumentNullException(nameof(datasets), "Property is not nullable for class CreatePublicationsRequest.");

            if (tools.IsSet && tools.Value == null)
                throw new ArgumentNullException(nameof(tools), "Property is not nullable for class CreatePublicationsRequest.");

            return new CreatePublicationsRequest(paperTitle, authors, yearOfPublication, paperDoi, publicationType, journalName, varAbstract, url, mongoId, datasets, tools);
        }

        /// <summary>
        /// Serializes a <see cref="CreatePublicationsRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createPublicationsRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreatePublicationsRequest createPublicationsRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createPublicationsRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreatePublicationsRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createPublicationsRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreatePublicationsRequest createPublicationsRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createPublicationsRequest.PaperTitleOption.IsSet && createPublicationsRequest.PaperTitle == null)
                throw new ArgumentNullException(nameof(createPublicationsRequest.PaperTitle), "Property is required for class CreatePublicationsRequest.");

            if (createPublicationsRequest.AuthorsOption.IsSet && createPublicationsRequest.Authors == null)
                throw new ArgumentNullException(nameof(createPublicationsRequest.Authors), "Property is required for class CreatePublicationsRequest.");

            if (createPublicationsRequest.YearOfPublicationOption.IsSet && createPublicationsRequest.YearOfPublication == null)
                throw new ArgumentNullException(nameof(createPublicationsRequest.YearOfPublication), "Property is required for class CreatePublicationsRequest.");

            if (createPublicationsRequest.PaperDoiOption.IsSet && createPublicationsRequest.PaperDoi == null)
                throw new ArgumentNullException(nameof(createPublicationsRequest.PaperDoi), "Property is required for class CreatePublicationsRequest.");

            if (createPublicationsRequest.PublicationTypeOption.IsSet && createPublicationsRequest.PublicationType == null)
                throw new ArgumentNullException(nameof(createPublicationsRequest.PublicationType), "Property is required for class CreatePublicationsRequest.");

            if (createPublicationsRequest.JournalNameOption.IsSet && createPublicationsRequest.JournalName == null)
                throw new ArgumentNullException(nameof(createPublicationsRequest.JournalName), "Property is required for class CreatePublicationsRequest.");

            if (createPublicationsRequest.AbstractOption.IsSet && createPublicationsRequest.Abstract == null)
                throw new ArgumentNullException(nameof(createPublicationsRequest.Abstract), "Property is required for class CreatePublicationsRequest.");

            if (createPublicationsRequest.UrlOption.IsSet && createPublicationsRequest.Url == null)
                throw new ArgumentNullException(nameof(createPublicationsRequest.Url), "Property is required for class CreatePublicationsRequest.");

            if (createPublicationsRequest.MongoIdOption.IsSet && createPublicationsRequest.MongoId == null)
                throw new ArgumentNullException(nameof(createPublicationsRequest.MongoId), "Property is required for class CreatePublicationsRequest.");

            if (createPublicationsRequest.DatasetsOption.IsSet && createPublicationsRequest.Datasets == null)
                throw new ArgumentNullException(nameof(createPublicationsRequest.Datasets), "Property is required for class CreatePublicationsRequest.");

            if (createPublicationsRequest.ToolsOption.IsSet && createPublicationsRequest.Tools == null)
                throw new ArgumentNullException(nameof(createPublicationsRequest.Tools), "Property is required for class CreatePublicationsRequest.");

            if (createPublicationsRequest.PaperTitleOption.IsSet)
                writer.WriteString("paper_title", createPublicationsRequest.PaperTitle);

            if (createPublicationsRequest.AuthorsOption.IsSet)
                writer.WriteString("authors", createPublicationsRequest.Authors);

            if (createPublicationsRequest.YearOfPublicationOption.IsSet)
                writer.WriteString("year_of_publication", createPublicationsRequest.YearOfPublication);

            if (createPublicationsRequest.PaperDoiOption.IsSet)
                writer.WriteString("paper_doi", createPublicationsRequest.PaperDoi);

            if (createPublicationsRequest.PublicationTypeOption.IsSet)
                writer.WriteString("publication_type", createPublicationsRequest.PublicationType);

            if (createPublicationsRequest.JournalNameOption.IsSet)
                writer.WriteString("journal_name", createPublicationsRequest.JournalName);

            if (createPublicationsRequest.AbstractOption.IsSet)
                writer.WriteString("abstract", createPublicationsRequest.Abstract);

            if (createPublicationsRequest.UrlOption.IsSet)
                writer.WriteString("url", createPublicationsRequest.Url);

            if (createPublicationsRequest.MongoIdOption.IsSet)
                writer.WriteString("mongo_id", createPublicationsRequest.MongoId);

            if (createPublicationsRequest.DatasetsOption.IsSet)
            {
                writer.WritePropertyName("datasets");
                JsonSerializer.Serialize(writer, createPublicationsRequest.Datasets, jsonSerializerOptions);
            }
            if (createPublicationsRequest.ToolsOption.IsSet)
            {
                writer.WritePropertyName("tools");
                JsonSerializer.Serialize(writer, createPublicationsRequest.Tools, jsonSerializerOptions);
            }
        }
    }
}
