// <auto-generated>
/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using GatewayApiSdk.Client;

namespace GatewayApiSdk.Model
{
    /// <summary>
    /// CreateDarSectionRequest
    /// </summary>
    public partial class CreateDarSectionRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateDarSectionRequest" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="description">description</param>
        /// <param name="order">order</param>
        /// <param name="parentSection">parentSection</param>
        [JsonConstructor]
        public CreateDarSectionRequest(string name, string description, int order, Option<int?> parentSection = default)
        {
            Name = name;
            Description = description;
            Order = order;
            ParentSectionOption = parentSection;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        /* <example>Safe People</example> */
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        /* <example>Who has access?</example> */
        [JsonPropertyName("description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Order
        /// </summary>
        /* <example>1</example> */
        [JsonPropertyName("order")]
        public int Order { get; set; }

        /// <summary>
        /// Used to track the state of ParentSection
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ParentSectionOption { get; private set; }

        /// <summary>
        /// Gets or Sets ParentSection
        /// </summary>
        /* <example>1</example> */
        [JsonPropertyName("parent_section")]
        public int? ParentSection { get { return this.ParentSectionOption.Value; } set { this.ParentSectionOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateDarSectionRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Order: ").Append(Order).Append("\n");
            sb.Append("  ParentSection: ").Append(ParentSection).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateDarSectionRequest" />
    /// </summary>
    public partial class CreateDarSectionRequestJsonConverter : JsonConverter<CreateDarSectionRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateDarSectionRequestJsonConverter" /> class.
        /// </summary>
        public CreateDarSectionRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="CreateDarSectionRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateDarSectionRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> description = default;
            Option<int?> order = default;
            Option<int?> parentSection = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "order":
                            order = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "parent_section":
                            parentSection = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class CreateDarSectionRequest.", nameof(name));

            if (!description.IsSet)
                throw new ArgumentException("Property is required for class CreateDarSectionRequest.", nameof(description));

            if (!order.IsSet)
                throw new ArgumentException("Property is required for class CreateDarSectionRequest.", nameof(order));

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class CreateDarSectionRequest.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class CreateDarSectionRequest.");

            if (order.IsSet && order.Value == null)
                throw new ArgumentNullException(nameof(order), "Property is not nullable for class CreateDarSectionRequest.");

            if (parentSection.IsSet && parentSection.Value == null)
                throw new ArgumentNullException(nameof(parentSection), "Property is not nullable for class CreateDarSectionRequest.");

            return new CreateDarSectionRequest(name.Value!, description.Value!, order.Value!.Value!, parentSection);
        }

        /// <summary>
        /// Serializes a <see cref="CreateDarSectionRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createDarSectionRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateDarSectionRequest createDarSectionRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createDarSectionRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateDarSectionRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createDarSectionRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateDarSectionRequest createDarSectionRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createDarSectionRequest.Name == null)
                throw new ArgumentNullException(nameof(createDarSectionRequest.Name), "Property is required for class CreateDarSectionRequest.");

            if (createDarSectionRequest.Description == null)
                throw new ArgumentNullException(nameof(createDarSectionRequest.Description), "Property is required for class CreateDarSectionRequest.");

            writer.WriteString("name", createDarSectionRequest.Name);

            writer.WriteString("description", createDarSectionRequest.Description);

            writer.WriteNumber("order", createDarSectionRequest.Order);

            if (createDarSectionRequest.ParentSectionOption.IsSet)
                writer.WriteNumber("parent_section", createDarSectionRequest.ParentSectionOption.Value!.Value);
        }
    }
}
