// <auto-generated>
/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using GatewayApiSdk.Client;

namespace GatewayApiSdk.Model
{
    /// <summary>
    /// Fa314398c7a73002fee4ffc7e62e9fb6Request
    /// </summary>
    public partial class Fa314398c7a73002fee4ffc7e62e9fb6Request : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Fa314398c7a73002fee4ffc7e62e9fb6Request" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="filters">filters</param>
        /// <param name="enabled">enabled</param>
        [JsonConstructor]
        public Fa314398c7a73002fee4ffc7e62e9fb6Request(Option<string?> name = default, Option<List<Model39500344ecf1a14150bbe26c4a138c56RequestFiltersInner>?> filters = default, Option<string?> enabled = default)
        {
            NameOption = name;
            FiltersOption = filters;
            EnabledOption = enabled;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        /* <example>Name</example> */
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Filters
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Model39500344ecf1a14150bbe26c4a138c56RequestFiltersInner>?> FiltersOption { get; private set; }

        /// <summary>
        /// Gets or Sets Filters
        /// </summary>
        [JsonPropertyName("filters")]
        public List<Model39500344ecf1a14150bbe26c4a138c56RequestFiltersInner>? Filters { get { return this.FiltersOption.Value; } set { this.FiltersOption = new(value); } }

        /// <summary>
        /// Used to track the state of Enabled
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EnabledOption { get; private set; }

        /// <summary>
        /// Gets or Sets Enabled
        /// </summary>
        /* <example>true</example> */
        [JsonPropertyName("enabled")]
        public string? Enabled { get { return this.EnabledOption.Value; } set { this.EnabledOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Fa314398c7a73002fee4ffc7e62e9fb6Request {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Filters: ").Append(Filters).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Fa314398c7a73002fee4ffc7e62e9fb6Request" />
    /// </summary>
    public partial class Fa314398c7a73002fee4ffc7e62e9fb6RequestJsonConverter : JsonConverter<Fa314398c7a73002fee4ffc7e62e9fb6Request>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="Fa314398c7a73002fee4ffc7e62e9fb6RequestJsonConverter" /> class.
        /// </summary>
        public Fa314398c7a73002fee4ffc7e62e9fb6RequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="Fa314398c7a73002fee4ffc7e62e9fb6Request" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Fa314398c7a73002fee4ffc7e62e9fb6Request Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<List<Model39500344ecf1a14150bbe26c4a138c56RequestFiltersInner>?> filters = default;
            Option<string?> enabled = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "filters":
                            filters = new Option<List<Model39500344ecf1a14150bbe26c4a138c56RequestFiltersInner>?>(JsonSerializer.Deserialize<List<Model39500344ecf1a14150bbe26c4a138c56RequestFiltersInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "enabled":
                            enabled = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class Fa314398c7a73002fee4ffc7e62e9fb6Request.");

            if (filters.IsSet && filters.Value == null)
                throw new ArgumentNullException(nameof(filters), "Property is not nullable for class Fa314398c7a73002fee4ffc7e62e9fb6Request.");

            if (enabled.IsSet && enabled.Value == null)
                throw new ArgumentNullException(nameof(enabled), "Property is not nullable for class Fa314398c7a73002fee4ffc7e62e9fb6Request.");

            return new Fa314398c7a73002fee4ffc7e62e9fb6Request(name, filters, enabled);
        }

        /// <summary>
        /// Serializes a <see cref="Fa314398c7a73002fee4ffc7e62e9fb6Request" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="fa314398c7a73002fee4ffc7e62e9fb6Request"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Fa314398c7a73002fee4ffc7e62e9fb6Request fa314398c7a73002fee4ffc7e62e9fb6Request, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, fa314398c7a73002fee4ffc7e62e9fb6Request, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Fa314398c7a73002fee4ffc7e62e9fb6Request" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="fa314398c7a73002fee4ffc7e62e9fb6Request"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Fa314398c7a73002fee4ffc7e62e9fb6Request fa314398c7a73002fee4ffc7e62e9fb6Request, JsonSerializerOptions jsonSerializerOptions)
        {
            if (fa314398c7a73002fee4ffc7e62e9fb6Request.NameOption.IsSet && fa314398c7a73002fee4ffc7e62e9fb6Request.Name == null)
                throw new ArgumentNullException(nameof(fa314398c7a73002fee4ffc7e62e9fb6Request.Name), "Property is required for class Fa314398c7a73002fee4ffc7e62e9fb6Request.");

            if (fa314398c7a73002fee4ffc7e62e9fb6Request.FiltersOption.IsSet && fa314398c7a73002fee4ffc7e62e9fb6Request.Filters == null)
                throw new ArgumentNullException(nameof(fa314398c7a73002fee4ffc7e62e9fb6Request.Filters), "Property is required for class Fa314398c7a73002fee4ffc7e62e9fb6Request.");

            if (fa314398c7a73002fee4ffc7e62e9fb6Request.EnabledOption.IsSet && fa314398c7a73002fee4ffc7e62e9fb6Request.Enabled == null)
                throw new ArgumentNullException(nameof(fa314398c7a73002fee4ffc7e62e9fb6Request.Enabled), "Property is required for class Fa314398c7a73002fee4ffc7e62e9fb6Request.");

            if (fa314398c7a73002fee4ffc7e62e9fb6Request.NameOption.IsSet)
                writer.WriteString("name", fa314398c7a73002fee4ffc7e62e9fb6Request.Name);

            if (fa314398c7a73002fee4ffc7e62e9fb6Request.FiltersOption.IsSet)
            {
                writer.WritePropertyName("filters");
                JsonSerializer.Serialize(writer, fa314398c7a73002fee4ffc7e62e9fb6Request.Filters, jsonSerializerOptions);
            }
            if (fa314398c7a73002fee4ffc7e62e9fb6Request.EnabledOption.IsSet)
                writer.WriteString("enabled", fa314398c7a73002fee4ffc7e62e9fb6Request.Enabled);
        }
    }
}
