// <auto-generated>
/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using GatewayApiSdk.Client;

namespace GatewayApiSdk.Model
{
    /// <summary>
    /// FetchAliases200Response
    /// </summary>
    public partial class FetchAliases200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FetchAliases200Response" /> class.
        /// </summary>
        /// <param name="message">message</param>
        /// <param name="data">data</param>
        [JsonConstructor]
        public FetchAliases200Response(Option<string?> message = default, Option<Alias?> data = default)
        {
            MessageOption = message;
            DataOption = data;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Message
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [JsonPropertyName("message")]
        public string? Message { get { return this.MessageOption.Value; } set { this.MessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of Data
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Alias?> DataOption { get; private set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [JsonPropertyName("data")]
        public Alias? Data { get { return this.DataOption.Value; } set { this.DataOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FetchAliases200Response {\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="FetchAliases200Response" />
    /// </summary>
    public partial class FetchAliases200ResponseJsonConverter : JsonConverter<FetchAliases200Response>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="FetchAliases200ResponseJsonConverter" /> class.
        /// </summary>
        public FetchAliases200ResponseJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="FetchAliases200Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override FetchAliases200Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> message = default;
            Option<Alias?> data = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "data":
                            data = new Option<Alias?>(JsonSerializer.Deserialize<Alias>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class FetchAliases200Response.");

            if (data.IsSet && data.Value == null)
                throw new ArgumentNullException(nameof(data), "Property is not nullable for class FetchAliases200Response.");

            return new FetchAliases200Response(message, data);
        }

        /// <summary>
        /// Serializes a <see cref="FetchAliases200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="fetchAliases200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, FetchAliases200Response fetchAliases200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, fetchAliases200Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="FetchAliases200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="fetchAliases200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, FetchAliases200Response fetchAliases200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (fetchAliases200Response.MessageOption.IsSet && fetchAliases200Response.Message == null)
                throw new ArgumentNullException(nameof(fetchAliases200Response.Message), "Property is required for class FetchAliases200Response.");

            if (fetchAliases200Response.DataOption.IsSet && fetchAliases200Response.Data == null)
                throw new ArgumentNullException(nameof(fetchAliases200Response.Data), "Property is required for class FetchAliases200Response.");

            if (fetchAliases200Response.MessageOption.IsSet)
                writer.WriteString("message", fetchAliases200Response.Message);

            if (fetchAliases200Response.DataOption.IsSet)
            {
                writer.WritePropertyName("data");
                JsonSerializer.Serialize(writer, fetchAliases200Response.Data, jsonSerializerOptions);
            }
        }
    }
}
