// <auto-generated>
/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using GatewayApiSdk.Client;

namespace GatewayApiSdk.Model
{
    /// <summary>
    /// GetFederationHistory200ResponseDataInnerFailedDatasetsInner
    /// </summary>
    public partial class GetFederationHistory200ResponseDataInnerFailedDatasetsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetFederationHistory200ResponseDataInnerFailedDatasetsInner" /> class.
        /// </summary>
        /// <param name="pid">pid</param>
        /// <param name="message">message</param>
        [JsonConstructor]
        public GetFederationHistory200ResponseDataInnerFailedDatasetsInner(Option<string?> pid = default, Option<string?> message = default)
        {
            PidOption = pid;
            MessageOption = message;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Pid
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PidOption { get; private set; }

        /// <summary>
        /// Gets or Sets Pid
        /// </summary>
        /* <example>9c1e2f3a-...-abcdef</example> */
        [JsonPropertyName("pid")]
        public string? Pid { get { return this.PidOption.Value; } set { this.PidOption = new(value); } }

        /// <summary>
        /// Used to track the state of Message
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        /* <example>HDRUK/2.0.2: must NOT have additional properties</example> */
        [JsonPropertyName("message")]
        public string? Message { get { return this.MessageOption.Value; } set { this.MessageOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetFederationHistory200ResponseDataInnerFailedDatasetsInner {\n");
            sb.Append("  Pid: ").Append(Pid).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetFederationHistory200ResponseDataInnerFailedDatasetsInner" />
    /// </summary>
    public partial class GetFederationHistory200ResponseDataInnerFailedDatasetsInnerJsonConverter : JsonConverter<GetFederationHistory200ResponseDataInnerFailedDatasetsInner>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="GetFederationHistory200ResponseDataInnerFailedDatasetsInnerJsonConverter" /> class.
        /// </summary>
        public GetFederationHistory200ResponseDataInnerFailedDatasetsInnerJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="GetFederationHistory200ResponseDataInnerFailedDatasetsInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetFederationHistory200ResponseDataInnerFailedDatasetsInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> pid = default;
            Option<string?> message = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "pid":
                            pid = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (pid.IsSet && pid.Value == null)
                throw new ArgumentNullException(nameof(pid), "Property is not nullable for class GetFederationHistory200ResponseDataInnerFailedDatasetsInner.");

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class GetFederationHistory200ResponseDataInnerFailedDatasetsInner.");

            return new GetFederationHistory200ResponseDataInnerFailedDatasetsInner(pid, message);
        }

        /// <summary>
        /// Serializes a <see cref="GetFederationHistory200ResponseDataInnerFailedDatasetsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getFederationHistory200ResponseDataInnerFailedDatasetsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetFederationHistory200ResponseDataInnerFailedDatasetsInner getFederationHistory200ResponseDataInnerFailedDatasetsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getFederationHistory200ResponseDataInnerFailedDatasetsInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetFederationHistory200ResponseDataInnerFailedDatasetsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getFederationHistory200ResponseDataInnerFailedDatasetsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetFederationHistory200ResponseDataInnerFailedDatasetsInner getFederationHistory200ResponseDataInnerFailedDatasetsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getFederationHistory200ResponseDataInnerFailedDatasetsInner.PidOption.IsSet && getFederationHistory200ResponseDataInnerFailedDatasetsInner.Pid == null)
                throw new ArgumentNullException(nameof(getFederationHistory200ResponseDataInnerFailedDatasetsInner.Pid), "Property is required for class GetFederationHistory200ResponseDataInnerFailedDatasetsInner.");

            if (getFederationHistory200ResponseDataInnerFailedDatasetsInner.MessageOption.IsSet && getFederationHistory200ResponseDataInnerFailedDatasetsInner.Message == null)
                throw new ArgumentNullException(nameof(getFederationHistory200ResponseDataInnerFailedDatasetsInner.Message), "Property is required for class GetFederationHistory200ResponseDataInnerFailedDatasetsInner.");

            if (getFederationHistory200ResponseDataInnerFailedDatasetsInner.PidOption.IsSet)
                writer.WriteString("pid", getFederationHistory200ResponseDataInnerFailedDatasetsInner.Pid);

            if (getFederationHistory200ResponseDataInnerFailedDatasetsInner.MessageOption.IsSet)
                writer.WriteString("message", getFederationHistory200ResponseDataInnerFailedDatasetsInner.Message);
        }
    }
}
