// <auto-generated>
/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using GatewayApiSdk.Client;

namespace GatewayApiSdk.Model
{
    /// <summary>
    /// Model1fd84d2c66035574da4902f416cbd96aRequest
    /// </summary>
    public partial class Model1fd84d2c66035574da4902f416cbd96aRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Model1fd84d2c66035574da4902f416cbd96aRequest" /> class.
        /// </summary>
        /// <param name="notificationType">notificationType</param>
        /// <param name="message">message</param>
        /// <param name="optIn">optIn</param>
        /// <param name="enabled">enabled</param>
        /// <param name="email">email</param>
        [JsonConstructor]
        public Model1fd84d2c66035574da4902f416cbd96aRequest(string notificationType, string message, bool optIn, bool enabled, Option<string?> email = default)
        {
            NotificationType = notificationType;
            Message = message;
            OptIn = optIn;
            Enabled = enabled;
            EmailOption = email;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets NotificationType
        /// </summary>
        /* <example>applicationSubmitted</example> */
        [JsonPropertyName("notification_type")]
        public string NotificationType { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        /* <example>your message here</example> */
        [JsonPropertyName("message")]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets OptIn
        /// </summary>
        /* <example>false</example> */
        [JsonPropertyName("opt_in")]
        public bool OptIn { get; set; }

        /// <summary>
        /// Gets or Sets Enabled
        /// </summary>
        /* <example>false</example> */
        [JsonPropertyName("enabled")]
        public bool Enabled { get; set; }

        /// <summary>
        /// Used to track the state of Email
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> EmailOption { get; private set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        /* <example>john@example.com</example> */
        [JsonPropertyName("email")]
        public string? Email { get { return this.EmailOption.Value; } set { this.EmailOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Model1fd84d2c66035574da4902f416cbd96aRequest {\n");
            sb.Append("  NotificationType: ").Append(NotificationType).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  OptIn: ").Append(OptIn).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Model1fd84d2c66035574da4902f416cbd96aRequest" />
    /// </summary>
    public partial class Model1fd84d2c66035574da4902f416cbd96aRequestJsonConverter : JsonConverter<Model1fd84d2c66035574da4902f416cbd96aRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="Model1fd84d2c66035574da4902f416cbd96aRequestJsonConverter" /> class.
        /// </summary>
        public Model1fd84d2c66035574da4902f416cbd96aRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="Model1fd84d2c66035574da4902f416cbd96aRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Model1fd84d2c66035574da4902f416cbd96aRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> notificationType = default;
            Option<string?> message = default;
            Option<bool?> optIn = default;
            Option<bool?> enabled = default;
            Option<string?> email = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "notification_type":
                            notificationType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "opt_in":
                            optIn = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "enabled":
                            enabled = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "email":
                            email = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!notificationType.IsSet)
                throw new ArgumentException("Property is required for class Model1fd84d2c66035574da4902f416cbd96aRequest.", nameof(notificationType));

            if (!message.IsSet)
                throw new ArgumentException("Property is required for class Model1fd84d2c66035574da4902f416cbd96aRequest.", nameof(message));

            if (!optIn.IsSet)
                throw new ArgumentException("Property is required for class Model1fd84d2c66035574da4902f416cbd96aRequest.", nameof(optIn));

            if (!enabled.IsSet)
                throw new ArgumentException("Property is required for class Model1fd84d2c66035574da4902f416cbd96aRequest.", nameof(enabled));

            if (notificationType.IsSet && notificationType.Value == null)
                throw new ArgumentNullException(nameof(notificationType), "Property is not nullable for class Model1fd84d2c66035574da4902f416cbd96aRequest.");

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class Model1fd84d2c66035574da4902f416cbd96aRequest.");

            if (optIn.IsSet && optIn.Value == null)
                throw new ArgumentNullException(nameof(optIn), "Property is not nullable for class Model1fd84d2c66035574da4902f416cbd96aRequest.");

            if (enabled.IsSet && enabled.Value == null)
                throw new ArgumentNullException(nameof(enabled), "Property is not nullable for class Model1fd84d2c66035574da4902f416cbd96aRequest.");

            if (email.IsSet && email.Value == null)
                throw new ArgumentNullException(nameof(email), "Property is not nullable for class Model1fd84d2c66035574da4902f416cbd96aRequest.");

            return new Model1fd84d2c66035574da4902f416cbd96aRequest(notificationType.Value!, message.Value!, optIn.Value!.Value!, enabled.Value!.Value!, email);
        }

        /// <summary>
        /// Serializes a <see cref="Model1fd84d2c66035574da4902f416cbd96aRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="model1fd84d2c66035574da4902f416cbd96aRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Model1fd84d2c66035574da4902f416cbd96aRequest model1fd84d2c66035574da4902f416cbd96aRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, model1fd84d2c66035574da4902f416cbd96aRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Model1fd84d2c66035574da4902f416cbd96aRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="model1fd84d2c66035574da4902f416cbd96aRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Model1fd84d2c66035574da4902f416cbd96aRequest model1fd84d2c66035574da4902f416cbd96aRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (model1fd84d2c66035574da4902f416cbd96aRequest.NotificationType == null)
                throw new ArgumentNullException(nameof(model1fd84d2c66035574da4902f416cbd96aRequest.NotificationType), "Property is required for class Model1fd84d2c66035574da4902f416cbd96aRequest.");

            if (model1fd84d2c66035574da4902f416cbd96aRequest.Message == null)
                throw new ArgumentNullException(nameof(model1fd84d2c66035574da4902f416cbd96aRequest.Message), "Property is required for class Model1fd84d2c66035574da4902f416cbd96aRequest.");

            if (model1fd84d2c66035574da4902f416cbd96aRequest.EmailOption.IsSet && model1fd84d2c66035574da4902f416cbd96aRequest.Email == null)
                throw new ArgumentNullException(nameof(model1fd84d2c66035574da4902f416cbd96aRequest.Email), "Property is required for class Model1fd84d2c66035574da4902f416cbd96aRequest.");

            writer.WriteString("notification_type", model1fd84d2c66035574da4902f416cbd96aRequest.NotificationType);

            writer.WriteString("message", model1fd84d2c66035574da4902f416cbd96aRequest.Message);

            writer.WriteBoolean("opt_in", model1fd84d2c66035574da4902f416cbd96aRequest.OptIn);

            writer.WriteBoolean("enabled", model1fd84d2c66035574da4902f416cbd96aRequest.Enabled);

            if (model1fd84d2c66035574da4902f416cbd96aRequest.EmailOption.IsSet)
                writer.WriteString("email", model1fd84d2c66035574da4902f416cbd96aRequest.Email);
        }
    }
}
