// <auto-generated>
/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using GatewayApiSdk.Client;

namespace GatewayApiSdk.Model
{
    /// <summary>
    /// Model8db417727e7fe7c2e99206b060a3b882Request
    /// </summary>
    public partial class Model8db417727e7fe7c2e99206b060a3b882Request : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Model8db417727e7fe7c2e99206b060a3b882Request" /> class.
        /// </summary>
        /// <param name="query">query</param>
        [JsonConstructor]
        public Model8db417727e7fe7c2e99206b060a3b882Request(Option<string?> query = default)
        {
            QueryOption = query;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Query
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> QueryOption { get; private set; }

        /// <summary>
        /// Gets or Sets Query
        /// </summary>
        /* <example>diabetes data uses</example> */
        [JsonPropertyName("query")]
        public string? Query { get { return this.QueryOption.Value; } set { this.QueryOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Model8db417727e7fe7c2e99206b060a3b882Request {\n");
            sb.Append("  Query: ").Append(Query).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Model8db417727e7fe7c2e99206b060a3b882Request" />
    /// </summary>
    public partial class Model8db417727e7fe7c2e99206b060a3b882RequestJsonConverter : JsonConverter<Model8db417727e7fe7c2e99206b060a3b882Request>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="Model8db417727e7fe7c2e99206b060a3b882RequestJsonConverter" /> class.
        /// </summary>
        public Model8db417727e7fe7c2e99206b060a3b882RequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="Model8db417727e7fe7c2e99206b060a3b882Request" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Model8db417727e7fe7c2e99206b060a3b882Request Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> query = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "query":
                            query = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (query.IsSet && query.Value == null)
                throw new ArgumentNullException(nameof(query), "Property is not nullable for class Model8db417727e7fe7c2e99206b060a3b882Request.");

            return new Model8db417727e7fe7c2e99206b060a3b882Request(query);
        }

        /// <summary>
        /// Serializes a <see cref="Model8db417727e7fe7c2e99206b060a3b882Request" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="model8db417727e7fe7c2e99206b060a3b882Request"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Model8db417727e7fe7c2e99206b060a3b882Request model8db417727e7fe7c2e99206b060a3b882Request, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, model8db417727e7fe7c2e99206b060a3b882Request, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Model8db417727e7fe7c2e99206b060a3b882Request" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="model8db417727e7fe7c2e99206b060a3b882Request"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Model8db417727e7fe7c2e99206b060a3b882Request model8db417727e7fe7c2e99206b060a3b882Request, JsonSerializerOptions jsonSerializerOptions)
        {
            if (model8db417727e7fe7c2e99206b060a3b882Request.QueryOption.IsSet && model8db417727e7fe7c2e99206b060a3b882Request.Query == null)
                throw new ArgumentNullException(nameof(model8db417727e7fe7c2e99206b060a3b882Request.Query), "Property is required for class Model8db417727e7fe7c2e99206b060a3b882Request.");

            if (model8db417727e7fe7c2e99206b060a3b882Request.QueryOption.IsSet)
                writer.WriteString("query", model8db417727e7fe7c2e99206b060a3b882Request.Query);
        }
    }
}
