// <auto-generated>
/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using GatewayApiSdk.Client;

namespace GatewayApiSdk.Model
{
    /// <summary>
    /// Model2e155418e5f0de41829414447919439eRequest
    /// </summary>
    public partial class Model2e155418e5f0de41829414447919439eRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Model2e155418e5f0de41829414447919439eRequest" /> class.
        /// </summary>
        /// <param name="reason">reason</param>
        /// <param name="score">score</param>
        [JsonConstructor]
        public Model2e155418e5f0de41829414447919439eRequest(string reason, int score)
        {
            Reason = reason;
            Score = score;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Reason
        /// </summary>
        /* <example>Your feedback goes here...</example> */
        [JsonPropertyName("reason")]
        public string Reason { get; set; }

        /// <summary>
        /// Gets or Sets Score
        /// </summary>
        /* <example>1</example> */
        [JsonPropertyName("score")]
        public int Score { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Model2e155418e5f0de41829414447919439eRequest {\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  Score: ").Append(Score).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Model2e155418e5f0de41829414447919439eRequest" />
    /// </summary>
    public partial class Model2e155418e5f0de41829414447919439eRequestJsonConverter : JsonConverter<Model2e155418e5f0de41829414447919439eRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="Model2e155418e5f0de41829414447919439eRequestJsonConverter" /> class.
        /// </summary>
        public Model2e155418e5f0de41829414447919439eRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="Model2e155418e5f0de41829414447919439eRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Model2e155418e5f0de41829414447919439eRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> reason = default;
            Option<int?> score = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "reason":
                            reason = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "score":
                            score = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!reason.IsSet)
                throw new ArgumentException("Property is required for class Model2e155418e5f0de41829414447919439eRequest.", nameof(reason));

            if (!score.IsSet)
                throw new ArgumentException("Property is required for class Model2e155418e5f0de41829414447919439eRequest.", nameof(score));

            if (reason.IsSet && reason.Value == null)
                throw new ArgumentNullException(nameof(reason), "Property is not nullable for class Model2e155418e5f0de41829414447919439eRequest.");

            if (score.IsSet && score.Value == null)
                throw new ArgumentNullException(nameof(score), "Property is not nullable for class Model2e155418e5f0de41829414447919439eRequest.");

            return new Model2e155418e5f0de41829414447919439eRequest(reason.Value!, score.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="Model2e155418e5f0de41829414447919439eRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="model2e155418e5f0de41829414447919439eRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Model2e155418e5f0de41829414447919439eRequest model2e155418e5f0de41829414447919439eRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, model2e155418e5f0de41829414447919439eRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Model2e155418e5f0de41829414447919439eRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="model2e155418e5f0de41829414447919439eRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Model2e155418e5f0de41829414447919439eRequest model2e155418e5f0de41829414447919439eRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (model2e155418e5f0de41829414447919439eRequest.Reason == null)
                throw new ArgumentNullException(nameof(model2e155418e5f0de41829414447919439eRequest.Reason), "Property is required for class Model2e155418e5f0de41829414447919439eRequest.");

            writer.WriteString("reason", model2e155418e5f0de41829414447919439eRequest.Reason);

            writer.WriteNumber("score", model2e155418e5f0de41829414447919439eRequest.Score);
        }
    }
}
