// <auto-generated>
/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using GatewayApiSdk.Client;

namespace GatewayApiSdk.Model
{
    /// <summary>
    /// Model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInner
    /// </summary>
    public partial class Model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInner" /> class.
        /// </summary>
        /// <param name="laySummary">laySummary</param>
        [JsonConstructor]
        public Model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInner(Option<List<Object>?> laySummary = default)
        {
            LaySummaryOption = laySummary;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of LaySummary
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Object>?> LaySummaryOption { get; private set; }

        /// <summary>
        /// Gets or Sets LaySummary
        /// </summary>
        [JsonPropertyName("laySummary")]
        public List<Object>? LaySummary { get { return this.LaySummaryOption.Value; } set { this.LaySummaryOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInner {\n");
            sb.Append("  LaySummary: ").Append(LaySummary).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInner" />
    /// </summary>
    public partial class Model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInnerJsonConverter : JsonConverter<Model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInner>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="Model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInnerJsonConverter" /> class.
        /// </summary>
        public Model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInnerJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="Model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<Object>?> laySummary = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "laySummary":
                            laySummary = new Option<List<Object>?>(JsonSerializer.Deserialize<List<Object>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (laySummary.IsSet && laySummary.Value == null)
                throw new ArgumentNullException(nameof(laySummary), "Property is not nullable for class Model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInner.");

            return new Model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInner(laySummary);
        }

        /// <summary>
        /// Serializes a <see cref="Model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInner model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInner model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInner.LaySummaryOption.IsSet && model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInner.LaySummary == null)
                throw new ArgumentNullException(nameof(model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInner.LaySummary), "Property is required for class Model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInner.");

            if (model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInner.LaySummaryOption.IsSet)
            {
                writer.WritePropertyName("laySummary");
                JsonSerializer.Serialize(writer, model8db417727e7fe7c2e99206b060a3b882200ResponseDataInnerHighlightInner.LaySummary, jsonSerializerOptions);
            }
        }
    }
}
