// <auto-generated>
/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using GatewayApiSdk.Client;

namespace GatewayApiSdk.Model
{
    /// <summary>
    /// UpdateToolsRequest
    /// </summary>
    public partial class UpdateToolsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateToolsRequest" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="url">url</param>
        /// <param name="description">description</param>
        /// <param name="license">license</param>
        /// <param name="techStack">techStack</param>
        /// <param name="categoryId">categoryId</param>
        /// <param name="userId">userId</param>
        /// <param name="teamId">teamId</param>
        /// <param name="tags">tags</param>
        /// <param name="dataset">dataset</param>
        /// <param name="enabled">enabled</param>
        /// <param name="programmingLanguage">programmingLanguage</param>
        /// <param name="programmingPackage">programmingPackage</param>
        /// <param name="typeCategory">typeCategory</param>
        /// <param name="associatedAuthors">associatedAuthors</param>
        /// <param name="contactAddress">contactAddress</param>
        /// <param name="publications">publications</param>
        /// <param name="durs">durs</param>
        /// <param name="collections">collections</param>
        /// <param name="anyDataset">anyDataset</param>
        /// <param name="status">status</param>
        [JsonConstructor]
        public UpdateToolsRequest(Option<string?> name = default, Option<string?> url = default, Option<string?> description = default, Option<int?> license = default, Option<string?> techStack = default, Option<int?> categoryId = default, Option<int?> userId = default, Option<int?> teamId = default, Option<List<long>?> tags = default, Option<List<CreateToolsIntegrationsRequestDatasetInner>?> dataset = default, Option<int?> enabled = default, Option<List<long>?> programmingLanguage = default, Option<List<long>?> programmingPackage = default, Option<List<long>?> typeCategory = default, Option<string?> associatedAuthors = default, Option<string?> contactAddress = default, Option<List<CreateToolsIntegrationsRequestPublicationsInner>?> publications = default, Option<List<long>?> durs = default, Option<List<CreateToolsRequestCollectionsInner>?> collections = default, Option<bool?> anyDataset = default, Option<StatusEnum?> status = default)
        {
            NameOption = name;
            UrlOption = url;
            DescriptionOption = description;
            LicenseOption = license;
            TechStackOption = techStack;
            CategoryIdOption = categoryId;
            UserIdOption = userId;
            TeamIdOption = teamId;
            TagsOption = tags;
            DatasetOption = dataset;
            EnabledOption = enabled;
            ProgrammingLanguageOption = programmingLanguage;
            ProgrammingPackageOption = programmingPackage;
            TypeCategoryOption = typeCategory;
            AssociatedAuthorsOption = associatedAuthors;
            ContactAddressOption = contactAddress;
            PublicationsOption = publications;
            DursOption = durs;
            CollectionsOption = collections;
            AnyDatasetOption = anyDataset;
            StatusOption = status;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Status
        /// </summary>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum ACTIVE for value: ACTIVE
            /// </summary>
            ACTIVE = 1,

            /// <summary>
            /// Enum DRAFT for value: DRAFT
            /// </summary>
            DRAFT = 2,

            /// <summary>
            /// Enum ARCHIVED for value: ARCHIVED
            /// </summary>
            ARCHIVED = 3
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("ACTIVE"))
                return StatusEnum.ACTIVE;

            if (value.Equals("DRAFT"))
                return StatusEnum.DRAFT;

            if (value.Equals("ARCHIVED"))
                return StatusEnum.ARCHIVED;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("ACTIVE"))
                return StatusEnum.ACTIVE;

            if (value.Equals("DRAFT"))
                return StatusEnum.DRAFT;

            if (value.Equals("ARCHIVED"))
                return StatusEnum.ARCHIVED;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum? value)
        {
            if (value == StatusEnum.ACTIVE)
                return "ACTIVE";

            if (value == StatusEnum.DRAFT)
                return "DRAFT";

            if (value == StatusEnum.ARCHIVED)
                return "ARCHIVED";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<StatusEnum?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public StatusEnum? Status { get { return this.StatusOption.Value; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        /* <example>Similique sapiente est vero eum.</example> */
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption.Value; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Url
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> UrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        /* <example>http://steuber.info/itaque-rerum-quia-et-odit-dolores-quia-enim</example> */
        [JsonPropertyName("url")]
        public string? Url { get { return this.UrlOption.Value; } set { this.UrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        /* <example>Quod maiores id qui iusto. Aut qui velit qui aut nisi et officia. Ab inventore dolores ut quia quo. Quae veritatis fugiat ad vel.</example> */
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption.Value; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of License
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> LicenseOption { get; private set; }

        /// <summary>
        /// Gets or Sets License
        /// </summary>
        /* <example>1</example> */
        [JsonPropertyName("license")]
        public int? License { get { return this.LicenseOption.Value; } set { this.LicenseOption = new(value); } }

        /// <summary>
        /// Used to track the state of TechStack
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TechStackOption { get; private set; }

        /// <summary>
        /// Gets or Sets TechStack
        /// </summary>
        /* <example>Cumque molestias excepturi quam at.</example> */
        [JsonPropertyName("tech_stack")]
        public string? TechStack { get { return this.TechStackOption.Value; } set { this.TechStackOption = new(value); } }

        /// <summary>
        /// Used to track the state of CategoryId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> CategoryIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets CategoryId
        /// </summary>
        /* <example>1</example> */
        [JsonPropertyName("category_id")]
        public int? CategoryId { get { return this.CategoryIdOption.Value; } set { this.CategoryIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of UserId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> UserIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        /* <example>1</example> */
        [JsonPropertyName("user_id")]
        public int? UserId { get { return this.UserIdOption.Value; } set { this.UserIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of TeamId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TeamIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets TeamId
        /// </summary>
        /* <example>1</example> */
        [JsonPropertyName("team_id")]
        public int? TeamId { get { return this.TeamIdOption.Value; } set { this.TeamIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Tags
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<long>?> TagsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [JsonPropertyName("tags")]
        public List<long>? Tags { get { return this.TagsOption.Value; } set { this.TagsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Dataset
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<CreateToolsIntegrationsRequestDatasetInner>?> DatasetOption { get; private set; }

        /// <summary>
        /// Gets or Sets Dataset
        /// </summary>
        [JsonPropertyName("dataset")]
        public List<CreateToolsIntegrationsRequestDatasetInner>? Dataset { get { return this.DatasetOption.Value; } set { this.DatasetOption = new(value); } }

        /// <summary>
        /// Used to track the state of Enabled
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> EnabledOption { get; private set; }

        /// <summary>
        /// Gets or Sets Enabled
        /// </summary>
        /* <example>1</example> */
        [JsonPropertyName("enabled")]
        public int? Enabled { get { return this.EnabledOption.Value; } set { this.EnabledOption = new(value); } }

        /// <summary>
        /// Used to track the state of ProgrammingLanguage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<long>?> ProgrammingLanguageOption { get; private set; }

        /// <summary>
        /// Gets or Sets ProgrammingLanguage
        /// </summary>
        [JsonPropertyName("programming_language")]
        public List<long>? ProgrammingLanguage { get { return this.ProgrammingLanguageOption.Value; } set { this.ProgrammingLanguageOption = new(value); } }

        /// <summary>
        /// Used to track the state of ProgrammingPackage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<long>?> ProgrammingPackageOption { get; private set; }

        /// <summary>
        /// Gets or Sets ProgrammingPackage
        /// </summary>
        [JsonPropertyName("programming_package")]
        public List<long>? ProgrammingPackage { get { return this.ProgrammingPackageOption.Value; } set { this.ProgrammingPackageOption = new(value); } }

        /// <summary>
        /// Used to track the state of TypeCategory
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<long>?> TypeCategoryOption { get; private set; }

        /// <summary>
        /// Gets or Sets TypeCategory
        /// </summary>
        [JsonPropertyName("type_category")]
        public List<long>? TypeCategory { get { return this.TypeCategoryOption.Value; } set { this.TypeCategoryOption = new(value); } }

        /// <summary>
        /// Used to track the state of AssociatedAuthors
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AssociatedAuthorsOption { get; private set; }

        /// <summary>
        /// Gets or Sets AssociatedAuthors
        /// </summary>
        /* <example>string</example> */
        [JsonPropertyName("associated_authors")]
        public string? AssociatedAuthors { get { return this.AssociatedAuthorsOption.Value; } set { this.AssociatedAuthorsOption = new(value); } }

        /// <summary>
        /// Used to track the state of ContactAddress
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ContactAddressOption { get; private set; }

        /// <summary>
        /// Gets or Sets ContactAddress
        /// </summary>
        /* <example>string</example> */
        [JsonPropertyName("contact_address")]
        public string? ContactAddress { get { return this.ContactAddressOption.Value; } set { this.ContactAddressOption = new(value); } }

        /// <summary>
        /// Used to track the state of Publications
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<CreateToolsIntegrationsRequestPublicationsInner>?> PublicationsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Publications
        /// </summary>
        [JsonPropertyName("publications")]
        public List<CreateToolsIntegrationsRequestPublicationsInner>? Publications { get { return this.PublicationsOption.Value; } set { this.PublicationsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Durs
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<long>?> DursOption { get; private set; }

        /// <summary>
        /// Gets or Sets Durs
        /// </summary>
        [JsonPropertyName("durs")]
        public List<long>? Durs { get { return this.DursOption.Value; } set { this.DursOption = new(value); } }

        /// <summary>
        /// Used to track the state of Collections
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<CreateToolsRequestCollectionsInner>?> CollectionsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Collections
        /// </summary>
        [JsonPropertyName("collections")]
        public List<CreateToolsRequestCollectionsInner>? Collections { get { return this.CollectionsOption.Value; } set { this.CollectionsOption = new(value); } }

        /// <summary>
        /// Used to track the state of AnyDataset
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> AnyDatasetOption { get; private set; }

        /// <summary>
        /// Gets or Sets AnyDataset
        /// </summary>
        /* <example>false</example> */
        [JsonPropertyName("any_dataset")]
        public bool? AnyDataset { get { return this.AnyDatasetOption.Value; } set { this.AnyDatasetOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateToolsRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  License: ").Append(License).Append("\n");
            sb.Append("  TechStack: ").Append(TechStack).Append("\n");
            sb.Append("  CategoryId: ").Append(CategoryId).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  TeamId: ").Append(TeamId).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  Dataset: ").Append(Dataset).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  ProgrammingLanguage: ").Append(ProgrammingLanguage).Append("\n");
            sb.Append("  ProgrammingPackage: ").Append(ProgrammingPackage).Append("\n");
            sb.Append("  TypeCategory: ").Append(TypeCategory).Append("\n");
            sb.Append("  AssociatedAuthors: ").Append(AssociatedAuthors).Append("\n");
            sb.Append("  ContactAddress: ").Append(ContactAddress).Append("\n");
            sb.Append("  Publications: ").Append(Publications).Append("\n");
            sb.Append("  Durs: ").Append(Durs).Append("\n");
            sb.Append("  Collections: ").Append(Collections).Append("\n");
            sb.Append("  AnyDataset: ").Append(AnyDataset).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UpdateToolsRequest" />
    /// </summary>
    public partial class UpdateToolsRequestJsonConverter : JsonConverter<UpdateToolsRequest>
    {
        partial void OnCreated();

        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateToolsRequestJsonConverter" /> class.
        /// </summary>
        public UpdateToolsRequestJsonConverter()
        {
            OnCreated();
        }

        /// <summary>
        /// Deserializes json to <see cref="UpdateToolsRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UpdateToolsRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> url = default;
            Option<string?> description = default;
            Option<int?> license = default;
            Option<string?> techStack = default;
            Option<int?> categoryId = default;
            Option<int?> userId = default;
            Option<int?> teamId = default;
            Option<List<long>?> tags = default;
            Option<List<CreateToolsIntegrationsRequestDatasetInner>?> dataset = default;
            Option<int?> enabled = default;
            Option<List<long>?> programmingLanguage = default;
            Option<List<long>?> programmingPackage = default;
            Option<List<long>?> typeCategory = default;
            Option<string?> associatedAuthors = default;
            Option<string?> contactAddress = default;
            Option<List<CreateToolsIntegrationsRequestPublicationsInner>?> publications = default;
            Option<List<long>?> durs = default;
            Option<List<CreateToolsRequestCollectionsInner>?> collections = default;
            Option<bool?> anyDataset = default;
            Option<UpdateToolsRequest.StatusEnum?> status = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "url":
                            url = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "license":
                            license = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "tech_stack":
                            techStack = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "category_id":
                            categoryId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "user_id":
                            userId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "team_id":
                            teamId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "tags":
                            tags = new Option<List<long>?>(JsonSerializer.Deserialize<List<long>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "dataset":
                            dataset = new Option<List<CreateToolsIntegrationsRequestDatasetInner>?>(JsonSerializer.Deserialize<List<CreateToolsIntegrationsRequestDatasetInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "enabled":
                            enabled = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "programming_language":
                            programmingLanguage = new Option<List<long>?>(JsonSerializer.Deserialize<List<long>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "programming_package":
                            programmingPackage = new Option<List<long>?>(JsonSerializer.Deserialize<List<long>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "type_category":
                            typeCategory = new Option<List<long>?>(JsonSerializer.Deserialize<List<long>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "associated_authors":
                            associatedAuthors = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "contact_address":
                            contactAddress = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "publications":
                            publications = new Option<List<CreateToolsIntegrationsRequestPublicationsInner>?>(JsonSerializer.Deserialize<List<CreateToolsIntegrationsRequestPublicationsInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "durs":
                            durs = new Option<List<long>?>(JsonSerializer.Deserialize<List<long>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "collections":
                            collections = new Option<List<CreateToolsRequestCollectionsInner>?>(JsonSerializer.Deserialize<List<CreateToolsRequestCollectionsInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "any_dataset":
                            anyDataset = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<UpdateToolsRequest.StatusEnum?>(UpdateToolsRequest.StatusEnumFromStringOrDefault(statusRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class UpdateToolsRequest.");

            if (url.IsSet && url.Value == null)
                throw new ArgumentNullException(nameof(url), "Property is not nullable for class UpdateToolsRequest.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class UpdateToolsRequest.");

            if (license.IsSet && license.Value == null)
                throw new ArgumentNullException(nameof(license), "Property is not nullable for class UpdateToolsRequest.");

            if (techStack.IsSet && techStack.Value == null)
                throw new ArgumentNullException(nameof(techStack), "Property is not nullable for class UpdateToolsRequest.");

            if (categoryId.IsSet && categoryId.Value == null)
                throw new ArgumentNullException(nameof(categoryId), "Property is not nullable for class UpdateToolsRequest.");

            if (userId.IsSet && userId.Value == null)
                throw new ArgumentNullException(nameof(userId), "Property is not nullable for class UpdateToolsRequest.");

            if (teamId.IsSet && teamId.Value == null)
                throw new ArgumentNullException(nameof(teamId), "Property is not nullable for class UpdateToolsRequest.");

            if (tags.IsSet && tags.Value == null)
                throw new ArgumentNullException(nameof(tags), "Property is not nullable for class UpdateToolsRequest.");

            if (dataset.IsSet && dataset.Value == null)
                throw new ArgumentNullException(nameof(dataset), "Property is not nullable for class UpdateToolsRequest.");

            if (enabled.IsSet && enabled.Value == null)
                throw new ArgumentNullException(nameof(enabled), "Property is not nullable for class UpdateToolsRequest.");

            if (programmingLanguage.IsSet && programmingLanguage.Value == null)
                throw new ArgumentNullException(nameof(programmingLanguage), "Property is not nullable for class UpdateToolsRequest.");

            if (programmingPackage.IsSet && programmingPackage.Value == null)
                throw new ArgumentNullException(nameof(programmingPackage), "Property is not nullable for class UpdateToolsRequest.");

            if (typeCategory.IsSet && typeCategory.Value == null)
                throw new ArgumentNullException(nameof(typeCategory), "Property is not nullable for class UpdateToolsRequest.");

            if (associatedAuthors.IsSet && associatedAuthors.Value == null)
                throw new ArgumentNullException(nameof(associatedAuthors), "Property is not nullable for class UpdateToolsRequest.");

            if (contactAddress.IsSet && contactAddress.Value == null)
                throw new ArgumentNullException(nameof(contactAddress), "Property is not nullable for class UpdateToolsRequest.");

            if (publications.IsSet && publications.Value == null)
                throw new ArgumentNullException(nameof(publications), "Property is not nullable for class UpdateToolsRequest.");

            if (durs.IsSet && durs.Value == null)
                throw new ArgumentNullException(nameof(durs), "Property is not nullable for class UpdateToolsRequest.");

            if (collections.IsSet && collections.Value == null)
                throw new ArgumentNullException(nameof(collections), "Property is not nullable for class UpdateToolsRequest.");

            if (anyDataset.IsSet && anyDataset.Value == null)
                throw new ArgumentNullException(nameof(anyDataset), "Property is not nullable for class UpdateToolsRequest.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class UpdateToolsRequest.");

            return new UpdateToolsRequest(name, url, description, license, techStack, categoryId, userId, teamId, tags, dataset, enabled, programmingLanguage, programmingPackage, typeCategory, associatedAuthors, contactAddress, publications, durs, collections, anyDataset, status);
        }

        /// <summary>
        /// Serializes a <see cref="UpdateToolsRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateToolsRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UpdateToolsRequest updateToolsRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, updateToolsRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UpdateToolsRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateToolsRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UpdateToolsRequest updateToolsRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (updateToolsRequest.NameOption.IsSet && updateToolsRequest.Name == null)
                throw new ArgumentNullException(nameof(updateToolsRequest.Name), "Property is required for class UpdateToolsRequest.");

            if (updateToolsRequest.UrlOption.IsSet && updateToolsRequest.Url == null)
                throw new ArgumentNullException(nameof(updateToolsRequest.Url), "Property is required for class UpdateToolsRequest.");

            if (updateToolsRequest.DescriptionOption.IsSet && updateToolsRequest.Description == null)
                throw new ArgumentNullException(nameof(updateToolsRequest.Description), "Property is required for class UpdateToolsRequest.");

            if (updateToolsRequest.TechStackOption.IsSet && updateToolsRequest.TechStack == null)
                throw new ArgumentNullException(nameof(updateToolsRequest.TechStack), "Property is required for class UpdateToolsRequest.");

            if (updateToolsRequest.TagsOption.IsSet && updateToolsRequest.Tags == null)
                throw new ArgumentNullException(nameof(updateToolsRequest.Tags), "Property is required for class UpdateToolsRequest.");

            if (updateToolsRequest.DatasetOption.IsSet && updateToolsRequest.Dataset == null)
                throw new ArgumentNullException(nameof(updateToolsRequest.Dataset), "Property is required for class UpdateToolsRequest.");

            if (updateToolsRequest.ProgrammingLanguageOption.IsSet && updateToolsRequest.ProgrammingLanguage == null)
                throw new ArgumentNullException(nameof(updateToolsRequest.ProgrammingLanguage), "Property is required for class UpdateToolsRequest.");

            if (updateToolsRequest.ProgrammingPackageOption.IsSet && updateToolsRequest.ProgrammingPackage == null)
                throw new ArgumentNullException(nameof(updateToolsRequest.ProgrammingPackage), "Property is required for class UpdateToolsRequest.");

            if (updateToolsRequest.TypeCategoryOption.IsSet && updateToolsRequest.TypeCategory == null)
                throw new ArgumentNullException(nameof(updateToolsRequest.TypeCategory), "Property is required for class UpdateToolsRequest.");

            if (updateToolsRequest.AssociatedAuthorsOption.IsSet && updateToolsRequest.AssociatedAuthors == null)
                throw new ArgumentNullException(nameof(updateToolsRequest.AssociatedAuthors), "Property is required for class UpdateToolsRequest.");

            if (updateToolsRequest.ContactAddressOption.IsSet && updateToolsRequest.ContactAddress == null)
                throw new ArgumentNullException(nameof(updateToolsRequest.ContactAddress), "Property is required for class UpdateToolsRequest.");

            if (updateToolsRequest.PublicationsOption.IsSet && updateToolsRequest.Publications == null)
                throw new ArgumentNullException(nameof(updateToolsRequest.Publications), "Property is required for class UpdateToolsRequest.");

            if (updateToolsRequest.DursOption.IsSet && updateToolsRequest.Durs == null)
                throw new ArgumentNullException(nameof(updateToolsRequest.Durs), "Property is required for class UpdateToolsRequest.");

            if (updateToolsRequest.CollectionsOption.IsSet && updateToolsRequest.Collections == null)
                throw new ArgumentNullException(nameof(updateToolsRequest.Collections), "Property is required for class UpdateToolsRequest.");

            if (updateToolsRequest.NameOption.IsSet)
                writer.WriteString("name", updateToolsRequest.Name);

            if (updateToolsRequest.UrlOption.IsSet)
                writer.WriteString("url", updateToolsRequest.Url);

            if (updateToolsRequest.DescriptionOption.IsSet)
                writer.WriteString("description", updateToolsRequest.Description);

            if (updateToolsRequest.LicenseOption.IsSet)
                writer.WriteNumber("license", updateToolsRequest.LicenseOption.Value!.Value);

            if (updateToolsRequest.TechStackOption.IsSet)
                writer.WriteString("tech_stack", updateToolsRequest.TechStack);

            if (updateToolsRequest.CategoryIdOption.IsSet)
                writer.WriteNumber("category_id", updateToolsRequest.CategoryIdOption.Value!.Value);

            if (updateToolsRequest.UserIdOption.IsSet)
                writer.WriteNumber("user_id", updateToolsRequest.UserIdOption.Value!.Value);

            if (updateToolsRequest.TeamIdOption.IsSet)
                writer.WriteNumber("team_id", updateToolsRequest.TeamIdOption.Value!.Value);

            if (updateToolsRequest.TagsOption.IsSet)
            {
                writer.WritePropertyName("tags");
                JsonSerializer.Serialize(writer, updateToolsRequest.Tags, jsonSerializerOptions);
            }
            if (updateToolsRequest.DatasetOption.IsSet)
            {
                writer.WritePropertyName("dataset");
                JsonSerializer.Serialize(writer, updateToolsRequest.Dataset, jsonSerializerOptions);
            }
            if (updateToolsRequest.EnabledOption.IsSet)
                writer.WriteNumber("enabled", updateToolsRequest.EnabledOption.Value!.Value);

            if (updateToolsRequest.ProgrammingLanguageOption.IsSet)
            {
                writer.WritePropertyName("programming_language");
                JsonSerializer.Serialize(writer, updateToolsRequest.ProgrammingLanguage, jsonSerializerOptions);
            }
            if (updateToolsRequest.ProgrammingPackageOption.IsSet)
            {
                writer.WritePropertyName("programming_package");
                JsonSerializer.Serialize(writer, updateToolsRequest.ProgrammingPackage, jsonSerializerOptions);
            }
            if (updateToolsRequest.TypeCategoryOption.IsSet)
            {
                writer.WritePropertyName("type_category");
                JsonSerializer.Serialize(writer, updateToolsRequest.TypeCategory, jsonSerializerOptions);
            }
            if (updateToolsRequest.AssociatedAuthorsOption.IsSet)
                writer.WriteString("associated_authors", updateToolsRequest.AssociatedAuthors);

            if (updateToolsRequest.ContactAddressOption.IsSet)
                writer.WriteString("contact_address", updateToolsRequest.ContactAddress);

            if (updateToolsRequest.PublicationsOption.IsSet)
            {
                writer.WritePropertyName("publications");
                JsonSerializer.Serialize(writer, updateToolsRequest.Publications, jsonSerializerOptions);
            }
            if (updateToolsRequest.DursOption.IsSet)
            {
                writer.WritePropertyName("durs");
                JsonSerializer.Serialize(writer, updateToolsRequest.Durs, jsonSerializerOptions);
            }
            if (updateToolsRequest.CollectionsOption.IsSet)
            {
                writer.WritePropertyName("collections");
                JsonSerializer.Serialize(writer, updateToolsRequest.Collections, jsonSerializerOptions);
            }
            if (updateToolsRequest.AnyDatasetOption.IsSet)
                writer.WriteBoolean("any_dataset", updateToolsRequest.AnyDatasetOption.Value!.Value);

            var statusRawValue = UpdateToolsRequest.StatusEnumToJsonValue(updateToolsRequest.StatusOption.Value!.Value);
            writer.WriteString("status", statusRawValue);
        }
    }
}
