/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using GatewayApiSdk.Api;
using GatewayApiSdk.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace GatewayApiSdk.Test.Api
{
    /// <summary>
    ///  Class for testing CategoryApi
    /// </summary>
    public sealed class CategoryApiTests : ApiTestsBase
    {
        private readonly ICategoryApi _instance;

        public CategoryApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<ICategoryApi>();
        }

        /// <summary>
        /// Test CreateCategories
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateCategoriesAsyncTest()
        {
            CreateCategoriesRequest createCategoriesRequest = default!;
            var response = await _instance.CreateCategoriesAsync(createCategoriesRequest);
            var model = response.Ok();
            Assert.IsType<CreateCategories200Response>(model);
        }

        /// <summary>
        /// Test DeleteCategories
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteCategoriesAsyncTest()
        {
            int id = default!;
            var response = await _instance.DeleteCategoriesAsync(id);
            var model = response.NotFound();
            Assert.IsType<FetchAliases404Response>(model);
        }

        /// <summary>
        /// Test EditCategories
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task EditCategoriesAsyncTest()
        {
            int id = default!;
            EditCategoriesRequest editCategoriesRequest = default!;
            var response = await _instance.EditCategoriesAsync(id, editCategoriesRequest);
            var model = response.NotFound();
            Assert.IsType<FetchAliases404Response>(model);
        }

        /// <summary>
        /// Test FetchAllCategories
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task FetchAllCategoriesAsyncTest()
        {
            Client.Option<int> perPage = default!;
            var response = await _instance.FetchAllCategoriesAsync(perPage);
            var model = response.Ok();
            Assert.IsType<FetchAllCategories200Response>(model);
        }

        /// <summary>
        /// Test FetchCategories
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task FetchCategoriesAsyncTest()
        {
            int id = default!;
            var response = await _instance.FetchCategoriesAsync(id);
            var model = response.Ok();
            Assert.IsType<FetchAllCategories200Response>(model);
        }

        /// <summary>
        /// Test UpdateCategories
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdateCategoriesAsyncTest()
        {
            int id = default!;
            UpdateCategoriesRequest updateCategoriesRequest = default!;
            var response = await _instance.UpdateCategoriesAsync(id, updateCategoriesRequest);
            var model = response.NotFound();
            Assert.IsType<FetchAliases404Response>(model);
        }
    }
}
