/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using GatewayApiSdk.Api;
using GatewayApiSdk.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace GatewayApiSdk.Test.Api
{
    /// <summary>
    ///  Class for testing PublicationApi
    /// </summary>
    public sealed class PublicationApiTests : ApiTestsBase
    {
        private readonly IPublicationApi _instance;

        public PublicationApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IPublicationApi>();
        }

        /// <summary>
        /// Test CountUniqueFieldsPublications
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CountUniqueFieldsPublicationsAsyncTest()
        {
            string field = default!;
            int ownerId = default!;
            Client.Option<int> teamId = default!;
            var response = await _instance.CountUniqueFieldsPublicationsAsync(field, ownerId, teamId);
            var model = response.Ok();
            Assert.IsType<CountUniqueFieldsCollections200Response>(model);
        }

        /// <summary>
        /// Test CreatePublications
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreatePublicationsAsyncTest()
        {
            CreatePublicationsRequest createPublicationsRequest = default!;
            var response = await _instance.CreatePublicationsAsync(createPublicationsRequest);
            var model = response.Created();
            Assert.IsType<CreateDarIntegration201Response>(model);
        }

        /// <summary>
        /// Test DeletePublications
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeletePublicationsAsyncTest()
        {
            int id = default!;
            var response = await _instance.DeletePublicationsAsync(id);
            var model = response.Ok();
            Assert.IsType<DeleteFederation200Response>(model);
        }

        /// <summary>
        /// Test EditPublications
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task EditPublicationsAsyncTest()
        {
            int id = default!;
            UpdatePublicationsRequest updatePublicationsRequest = default!;
            Client.Option<string> unarchive = default!;
            var response = await _instance.EditPublicationsAsync(id, updatePublicationsRequest, unarchive);
            var model = response.Ok();
            Assert.IsType<FetchPublications200Response>(model);
        }

        /// <summary>
        /// Test FetchAllPublications
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task FetchAllPublicationsAsyncTest()
        {
            Client.Option<string> paperTitle = default!;
            Client.Option<Int> ownerId = default!;
            Client.Option<Int> teamId = default!;
            Client.Option<string> status = default!;
            var response = await _instance.FetchAllPublicationsAsync(paperTitle, ownerId, teamId, status);
            var model = response.Ok();
            Assert.IsType<FetchAllPublications200Response>(model);
        }

        /// <summary>
        /// Test FetchAllPublicationsV2
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task FetchAllPublicationsV2AsyncTest()
        {
            Client.Option<string> paperTitle = default!;
            Client.Option<bool> withRelated = default!;
            Client.Option<int> perPage = default!;
            var response = await _instance.FetchAllPublicationsV2Async(paperTitle, withRelated, perPage);
            var model = response.Ok();
            Assert.IsType<FetchAllPublications200Response>(model);
        }

        /// <summary>
        /// Test FetchPublications
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task FetchPublicationsAsyncTest()
        {
            int id = default!;
            var response = await _instance.FetchPublicationsAsync(id);
            var model = response.Ok();
            Assert.IsType<FetchPublications200Response>(model);
        }

        /// <summary>
        /// Test FetchPublicationsV2
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task FetchPublicationsV2AsyncTest()
        {
            int id = default!;
            var response = await _instance.FetchPublicationsV2Async(id);
            var model = response.Ok();
            Assert.IsType<FetchPublications200Response>(model);
        }

        /// <summary>
        /// Test UpdatePublications
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdatePublicationsAsyncTest()
        {
            int id = default!;
            UpdatePublicationsRequest updatePublicationsRequest = default!;
            var response = await _instance.UpdatePublicationsAsync(id, updatePublicationsRequest);
            var model = response.Ok();
            Assert.IsType<FetchPublications200Response>(model);
        }
    }
}
