/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using GatewayApiSdk.Api;
using GatewayApiSdk.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace GatewayApiSdk.Test.Api
{
    /// <summary>
    ///  Class for testing TeamDashboardApi
    /// </summary>
    public sealed class TeamDashboardApiTests : ApiTestsBase
    {
        private readonly ITeamDashboardApi _instance;

        public TeamDashboardApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<ITeamDashboardApi>();
        }

        /// <summary>
        /// Test FetchCollectionsViewsV3
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task FetchCollectionsViewsV3AsyncTest()
        {
            int id = default!;
            Client.Option<DateOnly> startDate = default!;
            Client.Option<DateOnly> endDate = default!;
            var response = await _instance.FetchCollectionsViewsV3Async(id, startDate, endDate);
            var model = response.Ok();
            Assert.IsType<FetchCollectionsViewsV3200Response>(model);
        }

        /// <summary>
        /// Test FetchDarApplicationsApplicationTimelineV3
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task FetchDarApplicationsApplicationTimelineV3AsyncTest()
        {
            int id = default!;
            Client.Option<DateOnly> startDate = default!;
            Client.Option<DateOnly> endDate = default!;
            var response = await _instance.FetchDarApplicationsApplicationTimelineV3Async(id, startDate, endDate);
            var model = response.Ok();
            Assert.IsType<CreateWidget201Response>(model);
        }

        /// <summary>
        /// Test FetchDarApplicationsAverageTimeToApprovalV3
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task FetchDarApplicationsAverageTimeToApprovalV3AsyncTest()
        {
            int id = default!;
            Client.Option<DateOnly> startDate = default!;
            Client.Option<DateOnly> endDate = default!;
            var response = await _instance.FetchDarApplicationsAverageTimeToApprovalV3Async(id, startDate, endDate);
            var model = response.Ok();
            Assert.IsType<CreateWidget201Response>(model);
        }

        /// <summary>
        /// Test FetchDarApplicationsCurrentStatusV3
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task FetchDarApplicationsCurrentStatusV3AsyncTest()
        {
            int id = default!;
            Client.Option<DateOnly> startDate = default!;
            Client.Option<DateOnly> endDate = default!;
            var response = await _instance.FetchDarApplicationsCurrentStatusV3Async(id, startDate, endDate);
            var model = response.Ok();
            Assert.IsType<CreateWidget201Response>(model);
        }

        /// <summary>
        /// Test FetchDarApplicationsDashboardExportCsvV3
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task FetchDarApplicationsDashboardExportCsvV3AsyncTest()
        {
            int id = default!;
            Client.Option<DateOnly> startDate = default!;
            Client.Option<DateOnly> endDate = default!;
            var response = await _instance.FetchDarApplicationsDashboardExportCsvV3Async(id, startDate, endDate);
            var model = response.Ok();
            Assert.IsType<CreateWidget201Response>(model);
        }

        /// <summary>
        /// Test FetchDarApplicationsDashboardRequiredActionsExportCsvV3
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task FetchDarApplicationsDashboardRequiredActionsExportCsvV3AsyncTest()
        {
            int id = default!;
            var response = await _instance.FetchDarApplicationsDashboardRequiredActionsExportCsvV3Async(id);
            var model = response.Ok();
            Assert.IsType<CreateWidget201Response>(model);
        }

        /// <summary>
        /// Test FetchDarApplicationsDashboardTimelineExportCsvV3
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task FetchDarApplicationsDashboardTimelineExportCsvV3AsyncTest()
        {
            int id = default!;
            Client.Option<DateOnly> startDate = default!;
            Client.Option<DateOnly> endDate = default!;
            var response = await _instance.FetchDarApplicationsDashboardTimelineExportCsvV3Async(id, startDate, endDate);
            var model = response.Ok();
            Assert.IsType<CreateWidget201Response>(model);
        }

        /// <summary>
        /// Test FetchDarApplicationsRequiredActionsV3
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task FetchDarApplicationsRequiredActionsV3AsyncTest()
        {
            int id = default!;
            Client.Option<DateOnly> startDate = default!;
            Client.Option<DateOnly> endDate = default!;
            var response = await _instance.FetchDarApplicationsRequiredActionsV3Async(id, startDate, endDate);
            var model = response.Ok();
            Assert.IsType<CreateWidget201Response>(model);
        }

        /// <summary>
        /// Test FetchDarMyApplicationsV3
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task FetchDarMyApplicationsV3AsyncTest()
        {
            int id = default!;
            Client.Option<DateOnly> startDate = default!;
            Client.Option<DateOnly> endDate = default!;
            var response = await _instance.FetchDarMyApplicationsV3Async(id, startDate, endDate);
            var model = response.Ok();
            Assert.IsType<CreateWidget201Response>(model);
        }

        /// <summary>
        /// Test FetchDashboardDownloadCsvV3
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task FetchDashboardDownloadCsvV3AsyncTest()
        {
            int id = default!;
            Client.Option<DateOnly> startDate = default!;
            Client.Option<DateOnly> endDate = default!;
            var response = await _instance.FetchDashboardDownloadCsvV3Async(id, startDate, endDate);
            var model = response.Ok();
            Assert.IsType<System.IO.Stream>(model);
        }

        /// <summary>
        /// Test FetchDataCustodiansViewsV3
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task FetchDataCustodiansViewsV3AsyncTest()
        {
            int id = default!;
            Client.Option<DateOnly> startDate = default!;
            Client.Option<DateOnly> endDate = default!;
            var response = await _instance.FetchDataCustodiansViewsV3Async(id, startDate, endDate);
            var model = response.Ok();
            Assert.IsType<FetchCollectionsViewsV3200Response>(model);
        }

        /// <summary>
        /// Test FetchDatasetViews360V3
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task FetchDatasetViews360V3AsyncTest()
        {
            int id = default!;
            Client.Option<DateOnly> startDate = default!;
            Client.Option<DateOnly> endDate = default!;
            var response = await _instance.FetchDatasetViews360V3Async(id, startDate, endDate);
            var model = response.Ok();
            Assert.IsType<FetchDatasetViews360V3200Response>(model);
        }

        /// <summary>
        /// Test FetchDatasetViewsTopV3
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task FetchDatasetViewsTopV3AsyncTest()
        {
            int id = default!;
            Client.Option<DateOnly> startDate = default!;
            Client.Option<DateOnly> endDate = default!;
            var response = await _instance.FetchDatasetViewsTopV3Async(id, startDate, endDate);
            var model = response.Ok();
            Assert.IsType<FetchDatasetViewsTopV3200Response>(model);
        }

        /// <summary>
        /// Test FetchEntitiesCountV3
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task FetchEntitiesCountV3AsyncTest()
        {
            int id = default!;
            string entity = default!;
            Client.Option<DateOnly> startDate = default!;
            Client.Option<DateOnly> endDate = default!;
            var response = await _instance.FetchEntitiesCountV3Async(id, entity, startDate, endDate);
            var model = response.Ok();
            Assert.IsType<FetchEntitiesCountV3200Response>(model);
        }
    }
}
