/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GatewayApiSdk.Model;
using GatewayApiSdk.Client;
using System.Reflection;

namespace GatewayApiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing Aa33edfdace17b70600d964e0db4d44bRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Aa33edfdace17b70600d964e0db4d44bRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Aa33edfdace17b70600d964e0db4d44bRequest
        //private Aa33edfdace17b70600d964e0db4d44bRequest instance;

        public Aa33edfdace17b70600d964e0db4d44bRequestTests()
        {
            // TODO uncomment below to create an instance of Aa33edfdace17b70600d964e0db4d44bRequest
            //instance = new Aa33edfdace17b70600d964e0db4d44bRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Aa33edfdace17b70600d964e0db4d44bRequest
        /// </summary>
        [Fact]
        public void Aa33edfdace17b70600d964e0db4d44bRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" Aa33edfdace17b70600d964e0db4d44bRequest
            //Assert.IsType<Aa33edfdace17b70600d964e0db4d44bRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Query'
        /// </summary>
        [Fact]
        public void QueryTest()
        {
            // TODO unit test for the property 'Query'
        }
    }
}
