/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GatewayApiSdk.Model;
using GatewayApiSdk.Client;
using System.Reflection;

namespace GatewayApiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing C9939b681f1c7deb438e5d7a25ea9509200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class C9939b681f1c7deb438e5d7a25ea9509200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for C9939b681f1c7deb438e5d7a25ea9509200Response
        //private C9939b681f1c7deb438e5d7a25ea9509200Response instance;

        public C9939b681f1c7deb438e5d7a25ea9509200ResponseTests()
        {
            // TODO uncomment below to create an instance of C9939b681f1c7deb438e5d7a25ea9509200Response
            //instance = new C9939b681f1c7deb438e5d7a25ea9509200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of C9939b681f1c7deb438e5d7a25ea9509200Response
        /// </summary>
        [Fact]
        public void C9939b681f1c7deb438e5d7a25ea9509200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" C9939b681f1c7deb438e5d7a25ea9509200Response
            //Assert.IsType<C9939b681f1c7deb438e5d7a25ea9509200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
