/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GatewayApiSdk.Model;
using GatewayApiSdk.Client;
using System.Reflection;

namespace GatewayApiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing Ced8add57941554cde6a5fc53f6555e5200ResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Ced8add57941554cde6a5fc53f6555e5200ResponseDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Ced8add57941554cde6a5fc53f6555e5200ResponseData
        //private Ced8add57941554cde6a5fc53f6555e5200ResponseData instance;

        public Ced8add57941554cde6a5fc53f6555e5200ResponseDataTests()
        {
            // TODO uncomment below to create an instance of Ced8add57941554cde6a5fc53f6555e5200ResponseData
            //instance = new Ced8add57941554cde6a5fc53f6555e5200ResponseData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Ced8add57941554cde6a5fc53f6555e5200ResponseData
        /// </summary>
        [Fact]
        public void Ced8add57941554cde6a5fc53f6555e5200ResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" Ced8add57941554cde6a5fc53f6555e5200ResponseData
            //Assert.IsType<Ced8add57941554cde6a5fc53f6555e5200ResponseData>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'TeamsCounts'
        /// </summary>
        [Fact]
        public void TeamsCountsTest()
        {
            // TODO unit test for the property 'TeamsCounts'
        }
    }
}
