/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GatewayApiSdk.Model;
using GatewayApiSdk.Client;
using System.Reflection;

namespace GatewayApiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing CreateDarSectionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateDarSectionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateDarSectionRequest
        //private CreateDarSectionRequest instance;

        public CreateDarSectionRequestTests()
        {
            // TODO uncomment below to create an instance of CreateDarSectionRequest
            //instance = new CreateDarSectionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateDarSectionRequest
        /// </summary>
        [Fact]
        public void CreateDarSectionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateDarSectionRequest
            //Assert.IsType<CreateDarSectionRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Fact]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }

        /// <summary>
        /// Test the property 'ParentSection'
        /// </summary>
        [Fact]
        public void ParentSectionTest()
        {
            // TODO unit test for the property 'ParentSection'
        }
    }
}
