/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GatewayApiSdk.Model;
using GatewayApiSdk.Client;
using System.Reflection;

namespace GatewayApiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing CreateUserDarApplicationAnswersRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateUserDarApplicationAnswersRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateUserDarApplicationAnswersRequest
        //private CreateUserDarApplicationAnswersRequest instance;

        public CreateUserDarApplicationAnswersRequestTests()
        {
            // TODO uncomment below to create an instance of CreateUserDarApplicationAnswersRequest
            //instance = new CreateUserDarApplicationAnswersRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateUserDarApplicationAnswersRequest
        /// </summary>
        [Fact]
        public void CreateUserDarApplicationAnswersRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateUserDarApplicationAnswersRequest
            //Assert.IsType<CreateUserDarApplicationAnswersRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Answers'
        /// </summary>
        [Fact]
        public void AnswersTest()
        {
            // TODO unit test for the property 'Answers'
        }
    }
}
