/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GatewayApiSdk.Model;
using GatewayApiSdk.Client;
using System.Reflection;

namespace GatewayApiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing CreateSavedSearchesRequestFiltersInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateSavedSearchesRequestFiltersInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateSavedSearchesRequestFiltersInner
        //private CreateSavedSearchesRequestFiltersInner instance;

        public CreateSavedSearchesRequestFiltersInnerTests()
        {
            // TODO uncomment below to create an instance of CreateSavedSearchesRequestFiltersInner
            //instance = new CreateSavedSearchesRequestFiltersInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateSavedSearchesRequestFiltersInner
        /// </summary>
        [Fact]
        public void CreateSavedSearchesRequestFiltersInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateSavedSearchesRequestFiltersInner
            //Assert.IsType<CreateSavedSearchesRequestFiltersInner>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Terms'
        /// </summary>
        [Fact]
        public void TermsTest()
        {
            // TODO unit test for the property 'Terms'
        }
    }
}
