/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GatewayApiSdk.Model;
using GatewayApiSdk.Client;
using System.Reflection;

namespace GatewayApiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing Ed769d8210100bbcd0e3a11660d25dc0200ResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Ed769d8210100bbcd0e3a11660d25dc0200ResponseDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Ed769d8210100bbcd0e3a11660d25dc0200ResponseData
        //private Ed769d8210100bbcd0e3a11660d25dc0200ResponseData instance;

        public Ed769d8210100bbcd0e3a11660d25dc0200ResponseDataTests()
        {
            // TODO uncomment below to create an instance of Ed769d8210100bbcd0e3a11660d25dc0200ResponseData
            //instance = new Ed769d8210100bbcd0e3a11660d25dc0200ResponseData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Ed769d8210100bbcd0e3a11660d25dc0200ResponseData
        /// </summary>
        [Fact]
        public void Ed769d8210100bbcd0e3a11660d25dc0200ResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" Ed769d8210100bbcd0e3a11660d25dc0200ResponseData
            //Assert.IsType<Ed769d8210100bbcd0e3a11660d25dc0200ResponseData>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'ImgUrl'
        /// </summary>
        [Fact]
        public void ImgUrlTest()
        {
            // TODO unit test for the property 'ImgUrl'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Fact]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }

        /// <summary>
        /// Test the property 'Datasets'
        /// </summary>
        [Fact]
        public void DatasetsTest()
        {
            // TODO unit test for the property 'Datasets'
        }

        /// <summary>
        /// Test the property 'Durs'
        /// </summary>
        [Fact]
        public void DursTest()
        {
            // TODO unit test for the property 'Durs'
        }

        /// <summary>
        /// Test the property 'Tools'
        /// </summary>
        [Fact]
        public void ToolsTest()
        {
            // TODO unit test for the property 'Tools'
        }

        /// <summary>
        /// Test the property 'Publications'
        /// </summary>
        [Fact]
        public void PublicationsTest()
        {
            // TODO unit test for the property 'Publications'
        }

        /// <summary>
        /// Test the property 'Collections'
        /// </summary>
        [Fact]
        public void CollectionsTest()
        {
            // TODO unit test for the property 'Collections'
        }

        /// <summary>
        /// Test the property 'Service'
        /// </summary>
        [Fact]
        public void ServiceTest()
        {
            // TODO unit test for the property 'Service'
        }
    }
}
