/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GatewayApiSdk.Model;
using GatewayApiSdk.Client;
using System.Reflection;

namespace GatewayApiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing Fceeda218a8998a137b9d7692e7947b6200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Fceeda218a8998a137b9d7692e7947b6200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Fceeda218a8998a137b9d7692e7947b6200Response
        //private Fceeda218a8998a137b9d7692e7947b6200Response instance;

        public Fceeda218a8998a137b9d7692e7947b6200ResponseTests()
        {
            // TODO uncomment below to create an instance of Fceeda218a8998a137b9d7692e7947b6200Response
            //instance = new Fceeda218a8998a137b9d7692e7947b6200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Fceeda218a8998a137b9d7692e7947b6200Response
        /// </summary>
        [Fact]
        public void Fceeda218a8998a137b9d7692e7947b6200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" Fceeda218a8998a137b9d7692e7947b6200Response
            //Assert.IsType<Fceeda218a8998a137b9d7692e7947b6200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
