/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GatewayApiSdk.Model;
using GatewayApiSdk.Client;
using System.Reflection;

namespace GatewayApiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing FetchDataCustodianNetwork200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FetchDataCustodianNetwork200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FetchDataCustodianNetwork200Response
        //private FetchDataCustodianNetwork200Response instance;

        public FetchDataCustodianNetwork200ResponseTests()
        {
            // TODO uncomment below to create an instance of FetchDataCustodianNetwork200Response
            //instance = new FetchDataCustodianNetwork200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FetchDataCustodianNetwork200Response
        /// </summary>
        [Fact]
        public void FetchDataCustodianNetwork200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" FetchDataCustodianNetwork200Response
            //Assert.IsType<FetchDataCustodianNetwork200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
