/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GatewayApiSdk.Model;
using GatewayApiSdk.Client;
using System.Reflection;

namespace GatewayApiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing Model9ce0c491d34067e8cf15eb9e9b5ec147200ResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Model9ce0c491d34067e8cf15eb9e9b5ec147200ResponseDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Model9ce0c491d34067e8cf15eb9e9b5ec147200ResponseData
        //private Model9ce0c491d34067e8cf15eb9e9b5ec147200ResponseData instance;

        public Model9ce0c491d34067e8cf15eb9e9b5ec147200ResponseDataTests()
        {
            // TODO uncomment below to create an instance of Model9ce0c491d34067e8cf15eb9e9b5ec147200ResponseData
            //instance = new Model9ce0c491d34067e8cf15eb9e9b5ec147200ResponseData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Model9ce0c491d34067e8cf15eb9e9b5ec147200ResponseData
        /// </summary>
        [Fact]
        public void Model9ce0c491d34067e8cf15eb9e9b5ec147200ResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" Model9ce0c491d34067e8cf15eb9e9b5ec147200ResponseData
            //Assert.IsType<Model9ce0c491d34067e8cf15eb9e9b5ec147200ResponseData>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'ImgUrl'
        /// </summary>
        [Fact]
        public void ImgUrlTest()
        {
            // TODO unit test for the property 'ImgUrl'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Fact]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'Service'
        /// </summary>
        [Fact]
        public void ServiceTest()
        {
            // TODO unit test for the property 'Service'
        }
    }
}
