/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GatewayApiSdk.Model;
using GatewayApiSdk.Client;
using System.Reflection;

namespace GatewayApiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing Model928c1c4e39f13593bdec88641ee83120200ResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Model928c1c4e39f13593bdec88641ee83120200ResponseDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Model928c1c4e39f13593bdec88641ee83120200ResponseData
        //private Model928c1c4e39f13593bdec88641ee83120200ResponseData instance;

        public Model928c1c4e39f13593bdec88641ee83120200ResponseDataTests()
        {
            // TODO uncomment below to create an instance of Model928c1c4e39f13593bdec88641ee83120200ResponseData
            //instance = new Model928c1c4e39f13593bdec88641ee83120200ResponseData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Model928c1c4e39f13593bdec88641ee83120200ResponseData
        /// </summary>
        [Fact]
        public void Model928c1c4e39f13593bdec88641ee83120200ResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" Model928c1c4e39f13593bdec88641ee83120200ResponseData
            //Assert.IsType<Model928c1c4e39f13593bdec88641ee83120200ResponseData>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'DeletedAt'
        /// </summary>
        [Fact]
        public void DeletedAtTest()
        {
            // TODO unit test for the property 'DeletedAt'
        }

        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Fact]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }

        /// <summary>
        /// Test the property 'FileLocation'
        /// </summary>
        [Fact]
        public void FileLocationTest()
        {
            // TODO unit test for the property 'FileLocation'
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'ApplicationId'
        /// </summary>
        [Fact]
        public void ApplicationIdTest()
        {
            // TODO unit test for the property 'ApplicationId'
        }

        /// <summary>
        /// Test the property 'QuestionId'
        /// </summary>
        [Fact]
        public void QuestionIdTest()
        {
            // TODO unit test for the property 'QuestionId'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
    }
}
