/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GatewayApiSdk.Model;
using GatewayApiSdk.Client;
using System.Reflection;

namespace GatewayApiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing Model64d6f1d6c88cbcfccd3e511b29c394d6Request
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Model64d6f1d6c88cbcfccd3e511b29c394d6RequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Model64d6f1d6c88cbcfccd3e511b29c394d6Request
        //private Model64d6f1d6c88cbcfccd3e511b29c394d6Request instance;

        public Model64d6f1d6c88cbcfccd3e511b29c394d6RequestTests()
        {
            // TODO uncomment below to create an instance of Model64d6f1d6c88cbcfccd3e511b29c394d6Request
            //instance = new Model64d6f1d6c88cbcfccd3e511b29c394d6Request();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Model64d6f1d6c88cbcfccd3e511b29c394d6Request
        /// </summary>
        [Fact]
        public void Model64d6f1d6c88cbcfccd3e511b29c394d6RequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" Model64d6f1d6c88cbcfccd3e511b29c394d6Request
            //Assert.IsType<Model64d6f1d6c88cbcfccd3e511b29c394d6Request>(instance);
        }

        /// <summary>
        /// Test the property 'SectionId'
        /// </summary>
        [Fact]
        public void SectionIdTest()
        {
            // TODO unit test for the property 'SectionId'
        }

        /// <summary>
        /// Test the property 'ForceRequired'
        /// </summary>
        [Fact]
        public void ForceRequiredTest()
        {
            // TODO unit test for the property 'ForceRequired'
        }

        /// <summary>
        /// Test the property 'AllowGuidanceOverride'
        /// </summary>
        [Fact]
        public void AllowGuidanceOverrideTest()
        {
            // TODO unit test for the property 'AllowGuidanceOverride'
        }

        /// <summary>
        /// Test the property 'Guidance'
        /// </summary>
        [Fact]
        public void GuidanceTest()
        {
            // TODO unit test for the property 'Guidance'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Field'
        /// </summary>
        [Fact]
        public void FieldTest()
        {
            // TODO unit test for the property 'Field'
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'TeamIds'
        /// </summary>
        [Fact]
        public void TeamIdsTest()
        {
            // TODO unit test for the property 'TeamIds'
        }

        /// <summary>
        /// Test the property 'Locked'
        /// </summary>
        [Fact]
        public void LockedTest()
        {
            // TODO unit test for the property 'Locked'
        }

        /// <summary>
        /// Test the property 'Archived'
        /// </summary>
        [Fact]
        public void ArchivedTest()
        {
            // TODO unit test for the property 'Archived'
        }

        /// <summary>
        /// Test the property 'IsChild'
        /// </summary>
        [Fact]
        public void IsChildTest()
        {
            // TODO unit test for the property 'IsChild'
        }

        /// <summary>
        /// Test the property 'QuestionType'
        /// </summary>
        [Fact]
        public void QuestionTypeTest()
        {
            // TODO unit test for the property 'QuestionType'
        }

        /// <summary>
        /// Test the property 'Required'
        /// </summary>
        [Fact]
        public void RequiredTest()
        {
            // TODO unit test for the property 'Required'
        }

        /// <summary>
        /// Test the property 'Default'
        /// </summary>
        [Fact]
        public void DefaultTest()
        {
            // TODO unit test for the property 'Default'
        }
    }
}
