/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GatewayApiSdk.Model;
using GatewayApiSdk.Client;
using System.Reflection;

namespace GatewayApiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing Register200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Register200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Register200Response
        //private Register200Response instance;

        public Register200ResponseTests()
        {
            // TODO uncomment below to create an instance of Register200Response
            //instance = new Register200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Register200Response
        /// </summary>
        [Fact]
        public void Register200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" Register200Response
            //Assert.IsType<Register200Response>(instance);
        }

        /// <summary>
        /// Test the property 'AccessToken'
        /// </summary>
        [Fact]
        public void AccessTokenTest()
        {
            // TODO unit test for the property 'AccessToken'
        }

        /// <summary>
        /// Test the property 'TokenType'
        /// </summary>
        [Fact]
        public void TokenTypeTest()
        {
            // TODO unit test for the property 'TokenType'
        }

        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
    }
}
