/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GatewayApiSdk.Model;
using GatewayApiSdk.Client;
using System.Reflection;

namespace GatewayApiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing SearchDatasets200ResponseDataInnerSourceInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchDatasets200ResponseDataInnerSourceInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchDatasets200ResponseDataInnerSourceInner
        //private SearchDatasets200ResponseDataInnerSourceInner instance;

        public SearchDatasets200ResponseDataInnerSourceInnerTests()
        {
            // TODO uncomment below to create an instance of SearchDatasets200ResponseDataInnerSourceInner
            //instance = new SearchDatasets200ResponseDataInnerSourceInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchDatasets200ResponseDataInnerSourceInner
        /// </summary>
        [Fact]
        public void SearchDatasets200ResponseDataInnerSourceInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchDatasets200ResponseDataInnerSourceInner
            //Assert.IsType<SearchDatasets200ResponseDataInnerSourceInner>(instance);
        }

        /// <summary>
        /// Test the property 'Abstract'
        /// </summary>
        [Fact]
        public void AbstractTest()
        {
            // TODO unit test for the property 'Abstract'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Keywords'
        /// </summary>
        [Fact]
        public void KeywordsTest()
        {
            // TODO unit test for the property 'Keywords'
        }

        /// <summary>
        /// Test the property 'NamedEntities'
        /// </summary>
        [Fact]
        public void NamedEntitiesTest()
        {
            // TODO unit test for the property 'NamedEntities'
        }

        /// <summary>
        /// Test the property 'PublisherName'
        /// </summary>
        [Fact]
        public void PublisherNameTest()
        {
            // TODO unit test for the property 'PublisherName'
        }

        /// <summary>
        /// Test the property 'ShortTitle'
        /// </summary>
        [Fact]
        public void ShortTitleTest()
        {
            // TODO unit test for the property 'ShortTitle'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
    }
}
