/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GatewayApiSdk.Model;
using GatewayApiSdk.Client;
using System.Reflection;

namespace GatewayApiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing SearchSimilarDatasetsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchSimilarDatasetsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchSimilarDatasetsRequest
        //private SearchSimilarDatasetsRequest instance;

        public SearchSimilarDatasetsRequestTests()
        {
            // TODO uncomment below to create an instance of SearchSimilarDatasetsRequest
            //instance = new SearchSimilarDatasetsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchSimilarDatasetsRequest
        /// </summary>
        [Fact]
        public void SearchSimilarDatasetsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchSimilarDatasetsRequest
            //Assert.IsType<SearchSimilarDatasetsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
    }
}
