/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GatewayApiSdk.Model;
using GatewayApiSdk.Client;
using System.Reflection;

namespace GatewayApiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateCategoriesRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateCategoriesRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateCategoriesRequest
        //private UpdateCategoriesRequest instance;

        public UpdateCategoriesRequestTests()
        {
            // TODO uncomment below to create an instance of UpdateCategoriesRequest
            //instance = new UpdateCategoriesRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateCategoriesRequest
        /// </summary>
        [Fact]
        public void UpdateCategoriesRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateCategoriesRequest
            //Assert.IsType<UpdateCategoriesRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }
    }
}
