/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GatewayApiSdk.Model;
using GatewayApiSdk.Client;
using System.Reflection;

namespace GatewayApiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateLibraries200ResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateLibraries200ResponseDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateLibraries200ResponseData
        //private UpdateLibraries200ResponseData instance;

        public UpdateLibraries200ResponseDataTests()
        {
            // TODO uncomment below to create an instance of UpdateLibraries200ResponseData
            //instance = new UpdateLibraries200ResponseData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateLibraries200ResponseData
        /// </summary>
        [Fact]
        public void UpdateLibraries200ResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateLibraries200ResponseData
            //Assert.IsType<UpdateLibraries200ResponseData>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'Dataset'
        /// </summary>
        [Fact]
        public void DatasetTest()
        {
            // TODO unit test for the property 'Dataset'
        }
    }
}
