/*
 * HDRUK Gateway API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GatewayApiSdk.Model;
using GatewayApiSdk.Client;
using System.Reflection;

namespace GatewayApiSdk.Test.Model
{
    /// <summary>
    ///  Class for testing VerifySecondaryEmail200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VerifySecondaryEmail200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VerifySecondaryEmail200Response
        //private VerifySecondaryEmail200Response instance;

        public VerifySecondaryEmail200ResponseTests()
        {
            // TODO uncomment below to create an instance of VerifySecondaryEmail200Response
            //instance = new VerifySecondaryEmail200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VerifySecondaryEmail200Response
        /// </summary>
        [Fact]
        public void VerifySecondaryEmail200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" VerifySecondaryEmail200Response
            //Assert.IsType<VerifySecondaryEmail200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
